'use strict';

const CHANGELOG = [
  { v: 'v3.1.2', de: { title: 'Hilferessourcen und UI-Korrekturen', items: [
    '<strong>Zusätzliche Hilferessourcen</strong> — Unterstützte Vorschau-Kontexte können nun passende Shop-Plugin-Dokumentation und Download-Links anzeigen',
    '<strong>Plugin-Übersicht im Hilfe-Tab</strong> — Neue Ressourcenkarten bündeln Dokumentation, Downloads und Quellenhinweise übersichtlich an einer Stelle',
    '<strong>Footer-Ausrichtung</strong> — Externe Links bleiben als Gruppe rechtsbündig neben der Aktion zum Löschen lokaler Daten',
    '<strong>Lesbarere Hilfe-Navigation</strong> — Light-Mode-Kontrast und Hover-Verhalten der Hilfe-Chips wurden weiter geglättet',
    '<strong>Stabile Header-Chips</strong> — Feature-Blasen im Header bleiben auch beim Hover im hellen Vorschau-Modus lesbar',
    '<strong>Einheitlicher App-Name</strong> — Sichtbare Titel und Metadaten verwenden durchgehend Paygate Payment Tester',
    '<strong>Release-Metadaten</strong> — App-Version, Changelog und Anwendungscache sind auf diese Version abgestimmt',
  ]}, en: { title: 'Help Resources and Interface Fixes', items: [
    '<strong>Additional help resources</strong> — Supported preview contexts can now show matching shop-plugin documentation and download links',
    '<strong>Plugin overview in Help</strong> — New resource cards group documentation, downloads and source guidance in one place',
    '<strong>Footer alignment</strong> — External links stay grouped and right-aligned next to the action for clearing local data',
    '<strong>More readable Help navigation</strong> — Light-mode contrast and hover behaviour for Help chips have been smoothed out',
    '<strong>Stable header chips</strong> — Header feature chips remain readable on hover in light-mode preview contexts',
    '<strong>Consistent app name</strong> — Visible titles and metadata now consistently use Paygate Payment Tester',
    '<strong>Release metadata</strong> — App version, changelog and application cache are aligned with this version',
  ]}},
  { v: 'v3.1.1', de: { title: 'Statushinweise und UI-Feinschliff', items: [
    '<strong>Status-Tooltips</strong> — Fragezeichen erklären Suchweg, Payment ID/PayID und Transaction ID direkt an den Eingabefeldern',
    '<strong>Korrekte Response-Auswertung</strong> — Ein Hinweis stellt klar, dass <code>Status=OK</code> nur die erfolgreiche Verarbeitung der Abfrage bestätigt',
    '<strong>Zahlungsstand verständlich erklärt</strong> — <code>AmountAuth</code>, <code>AmountCap</code>, <code>AmountCred</code> und <code>LastStatus</code> werden in ihrer Bedeutung eingeordnet',
    '<strong>Neue Auswahl-Icons</strong> — Schnittstellen und Use Cases verwenden passende Inline-SVGs für eine schnellere visuelle Orientierung',
    '<strong>Aktuelle PWA-Metadaten</strong> — Der standardisierte <code>mobile-web-app-capable</code>-Tag behebt die Chromium-Warnung zum veralteten Apple-spezifischen Meta-Tag',
  ]}, en: { title: 'Status Guidance and Interface Polish', items: [
    '<strong>Status tooltips</strong> — Inline question marks explain lookup type, Payment ID/PayID and Transaction ID',
    '<strong>Correct response interpretation</strong> — Guidance clarifies that <code>Status=OK</code> only confirms successful processing of the inquiry',
    '<strong>Clear payment-state guidance</strong> — The meaning of <code>AmountAuth</code>, <code>AmountCap</code>, <code>AmountCred</code> and <code>LastStatus</code> is explained',
    '<strong>New selector icons</strong> — Interfaces and use cases use matching inline SVGs for faster visual orientation',
    '<strong>Current PWA metadata</strong> — The standard <code>mobile-web-app-capable</code> tag resolves the Chromium warning about the Apple-specific legacy tag',
  ]}},
  { v: 'v3.1.0', de: { title: 'Transaktionsstatusabfragen', items: [
    '<strong>Neue Use-Case-Auswahl</strong> — Schritt 2 heißt nun Request konfigurieren und trennt Zahlungserstellung und Transaktionsstatus klar voneinander',
    '<strong>Classic-Statusabfrage</strong> — <code>inquire.aspx</code> und <code>inquire24.aspx</code> erzeugen verschlüsselte Abfragen über PayID oder Transaction ID',
    '<strong>REST-V1-Statusabfrage</strong> — Der aktuelle Zahlungsstatus kann über Payment ID oder Transaction ID als GET-Request vorbereitet werden',
    '<strong>Mehrere Ausgabeformate</strong> — Body-lose GET-Requests stehen für cURL, PowerShell, Postman Collection und Raw HTTP bereit',
    '<strong>Passende Credential-Hinweise</strong> — Classic-Statusabfragen benötigen Merchant ID und Blowfish-Passwort, jedoch kein HMAC-Passwort',
    '<strong>Statusvorschau und Ausführung</strong> — Verschlüsselte Parameter, finale URL und eine direkte Classic-Ausführung werden in Schritt 3 angeboten',
    '<strong>Vorbereitung für MIT/CIT</strong> — Die Oberfläche zeigt den kommenden Use Case bereits an, ohne noch nicht geprüfte Request-Logik zu aktivieren',
    '<strong>Schnittstellen-Badges im Request-Log</strong> — Classic- und REST-Anfragen sind sofort unterscheidbar; bestehende Einträge werden anhand ihrer URL erkannt',
    '<strong>Präzisere Status-Logs</strong> — Statusabfragen kennzeichnen PayID beziehungsweise Transaction ID passend zum gewählten Suchweg',
    '<strong>Datenschutzfreundliche Callback-Defaults</strong> — Öffentliche Dienste wurden aus den voreingestellten Redirect-URLs entfernt',
    '<strong>Interner Callback-Empfänger</strong> — Bei HTTP/HTTPS ist der lokale Empfänger für neue Nutzer standardmäßig aktiv',
    '<strong>Optionale externe Demo</strong> — httpbingo.org kann bewusst eingesetzt werden und weist klar auf externe Verarbeitung und synthetische Testdaten hin',
    '<strong>Klare file://-Erklärung</strong> — Die Oberfläche erklärt direkt, warum automatische Callback-Rückgaben eine HTTP/HTTPS-Bereitstellung benötigen',
    '<strong>Neutrale Beispiel-URLs</strong> — Platzhalter verwenden die reservierte Domain <code>example.com</code> mit übersetzten Pfaden',
  ]}, en: { title: 'Transaction Status Inquiries', items: [
    '<strong>New use-case selector</strong> — Step 2 is now Configure Request and clearly separates payment creation from transaction-status inquiries',
    '<strong>Classic status inquiries</strong> — <code>inquire.aspx</code> and <code>inquire24.aspx</code> generate encrypted inquiries by PayID or Transaction ID',
    '<strong>REST V1 status inquiries</strong> — Current payment status can be prepared as a GET request using Payment ID or Transaction ID',
    '<strong>Multiple output formats</strong> — Body-less GET requests are available for cURL, PowerShell, Postman Collection and raw HTTP',
    '<strong>Context-specific credentials</strong> — Classic status inquiries require Merchant ID and Blowfish password but no HMAC password',
    '<strong>Status preview and execution</strong> — Step 3 provides encrypted parameters, the final URL and direct Classic execution',
    '<strong>MIT/CIT preparation</strong> — The interface exposes the future use case without enabling request logic that has not yet been reviewed',
    '<strong>Interface badges in Request Log</strong> — Classic and REST requests are immediately distinguishable, including existing entries detected by URL',
    '<strong>Clearer status logs</strong> — Status inquiries label PayID or Transaction ID according to the selected lookup method',
    '<strong>Privacy-conscious callback defaults</strong> — Public services were removed from the default redirect URLs',
    '<strong>Internal callback receiver</strong> — On HTTP/HTTPS deployments, the local receiver is enabled by default for new users',
    '<strong>Optional external demo</strong> — httpbingo.org can be selected deliberately with clear external-processing and synthetic-data guidance',
    '<strong>Clear file:// guidance</strong> — The interface explains why automatic callback returns require an HTTP/HTTPS deployment',
    '<strong>Neutral example URLs</strong> — Placeholders use the reserved <code>example.com</code> domain with translated paths',
  ]}},
  { v: 'v3.0.2', de: { title: 'Kleinere Design-Anpassungen', items: [
    '<strong>Visuelle Verfeinerungen</strong> — Darstellung und unterstützende Oberflächendetails wurden behutsam angepasst',
  ]}, en: { title: 'Minor Design Adjustments', items: [
    '<strong>Visual refinements</strong> — Refined the presentation and supporting interface details',
  ]}},
  { v: 'v3.0.1', de: { title: 'Optionale REST-Credentials', items: [
    '<strong>Klare Pflichtzuordnung</strong> — Schritt 1 ist für Classic Paygate erforderlich, für das Zusammenbauen von REST-Requests dagegen optional',
    '<strong>Dynamisches Navbar-Badge</strong> — Bei ausgewählter REST API zeigt Schritt 1 nun <code>Optional</code> statt <code>Payment Workflow</code>',
    '<strong>Kontextabhängiger Hinweis</strong> — Der Credential-Bereich erklärt passend zur gewählten Schnittstelle, welche Zugangsdaten tatsächlich benötigt werden',
    '<strong>Visuelle Gruppierung</strong> — Classic-Credentials und optionale REST-Authentifizierung sind als getrennte Bereiche gekennzeichnet und gewichtet',
    '<strong>Sichere Platzhalter</strong> — Merchant ID und REST API-Key sind nur für eine ausdrücklich eingebettete echte Authentifizierung nötig',
    '<strong>Aktualisierte Hilfe</strong> — Hilfeseite und README dokumentieren die credential-freie REST-Request-Erstellung',
    '<strong>REST-Tooltips</strong> — Fragezeichen erklären API-Version, Zahlungsart, Zielumgebung, Authentifizierung und Ausgabeformat direkt am jeweiligen Feld',
    '<strong>Transparenteres Glass-Design</strong> — Navbar, Footer, Workflow-, Hilfe- und Changelog-Flächen zeigen den Hintergrund deutlicher bei gleichzeitig stärkerem Blur',
    '<strong>Glass-Scrollbar</strong> — Sichtbare Scrollbars verwenden eine schmale transparente Spur sowie einen blau-violetten Glass-Thumb für Dark und Light Mode',
    '<strong>Frühe Credential-Prüfung</strong> — Die REST-Opt-in-Checkbox deaktiviert sich bei fehlenden Zugangsdaten wieder, öffnet Schritt 1 und fokussiert das erste fehlende Feld',
    '<strong>Profil-Löschdialog</strong> — Credential-Profile werden über einen zweisprachigen App-Dialog statt einer nativen Browsermeldung bestätigt',
  ]}, en: { title: 'Optional REST Credentials', items: [
    '<strong>Clear requirements</strong> — Step 1 is required for Classic Paygate but optional when assembling REST requests',
    '<strong>Dynamic navbar badge</strong> — When REST API is selected, Step 1 now displays <code>Optional</code> instead of <code>Payment Workflow</code>',
    '<strong>Context-specific guidance</strong> — The credential section explains which authentication data is actually needed for the selected interface',
    '<strong>Visual grouping</strong> — Classic credentials and optional REST authentication are labelled and visually weighted as separate sections',
    '<strong>Safe placeholders</strong> — Merchant ID and REST API key are only required when explicitly embedding real authentication into output',
    '<strong>Updated guidance</strong> — The Help view and README document credential-free REST request generation',
    '<strong>REST tooltips</strong> — Inline question marks explain API version, payment type, target environment, authentication and output format',
    '<strong>More transparent glass design</strong> — Navigation, footer, workflow, Help and Changelog surfaces reveal more of the background while using stronger blur',
    '<strong>Glass scrollbar</strong> — Visible scrollbars use a slim transparent track and a blue-violet glass thumb in dark and light mode',
    '<strong>Immediate credential validation</strong> — The REST opt-in checkbox switches off again when credentials are missing, opens Step 1 and focuses the first missing field',
    '<strong>Profile deletion dialog</strong> — Deleting credential profiles now uses a bilingual in-app confirmation instead of a native browser prompt',
  ]}},
  { v: 'v3.0.0', de: { title: 'REST Request Builder', items: [
    '<strong>Eine Payment-Strecke</strong> — Classic Paygate und REST API sind im bestehenden Payment Workflow auswählbar',
    '<strong>REST V1 und V2</strong> — Hosted Payment Page, Card Form und Pay By Link erzeugen versionsspezifische JSON-Requests und Endpunkte',
    '<strong>Korrektes V2-Schema</strong> — Checkout Sessions, Hosted Card Payments und Payment Links verwenden unter anderem <code>transId</code>, String-Descriptions und <code>Idempotency-Key</code>',
    '<strong>Umgebungen & Auth</strong> — Produktions- und Testserver sowie Basic Auth und OAuth2 Client Credentials stehen zur Auswahl',
    '<strong>Externe Ausführung</strong> — Ausgaben für cURL, PowerShell, Postman Collection v2.1 und Raw HTTP enthalten passende Hinweise',
    '<strong>Syntax-Highlighting</strong> — JSON-Payload und ausführbarer Request werden passend zum gewählten Format hervorgehoben',
    '<strong>Testkarten-Hinweis</strong> — Offizielle Testdaten sind verlinkt; Kartendaten werden nicht in den REST-Payload übernommen',
    '<strong>Sichere Standards</strong> — Der Browser sendet keine REST-Anfrage und verwendet standardmäßig Credential-Platzhalter',
    '<strong>Bewusstes Opt-in</strong> — Merchant-ID und REST API-Key werden nur nach expliziter Auswahl in die Ausgabe eingesetzt',
    '<strong>Lokale Profile</strong> — Der REST API-Key kann zusammen mit den bestehenden Credentials verschlüsselt gespeichert werden',
    '<strong>Klare Zuordnung</strong> — Der Classic-GET-URL-Erklärbereich erscheint nur im Classic-Ablauf; Navigations-Badges kennzeichnen Payment Workflow und Classic-Funktionen',
    '<strong>REST-Feature-Blasen</strong> — REST API V1/V2, JSON Builder sowie cURL, PowerShell und Postman erscheinen als zusätzliche Merkmale unter dem Haupttitel',
    '<strong>Bereinigte Bezeichnungen</strong> — REST-Versionstexte wurden vereinfacht und die sichtbare Produktbezeichnung wurde durchgängig auf Paygate vereinheitlicht',
    '<strong>Release-Metadaten</strong> — Footer, App-Metadaten, PWA-Cache und Dokumentation wurden auf Version 3.0.0 aktualisiert',
    '<strong>Stabile Workflow-Navigation</strong> — Die aktive Schrittanzeige folgt einer festen Linie unter der Navbar und bleibt bei Navigationsklicks konsistent; eingeklappte Karten zeigen keine innere Trennlinie mehr',
    '<strong>Vorschau-Leerzustand</strong> — Beim Wechsel zwischen Classic und REST zeigt Schritt 3 wieder zuverlässig einen zweisprachigen Wartehinweis statt einer leeren Karte',
    '<strong>Desktop-Navigation</strong> — Bei zu wenig Breite erscheinen automatisch Glass-Pfeile an den Navbar-Rändern; zusätzlich lässt sich die Navigation mit dem Mausrad horizontal bewegen',
    '<strong>Hilfeseite</strong> — Eine neue zweisprachige Navbar-Ansicht bündelt Integrationsvergleich, App-Anleitung, offizielle Dokumentation, Testdaten, Fehlercodes und Datenschutz',
    '<strong>Guide-Badge</strong> — Die Hilfe ist in der Navbar mit einem eigenen violetten Guide-Badge gekennzeichnet',
    '<strong>Beständige Badge-Farben</strong> — Payment Workflow, Classic und Guide behalten auch im aktiven Navigationszustand ihre grünen, blauen und violetten Gruppenfarben',
    '<strong>Einheitlicher Wartehinweis</strong> — Der Leerzustand in Schritt 3 verwendet nun den normalen Inline-Hinweisstil mit sauber ausgerichtetem Icon und Text',
    '<strong>Ressourcen-Icons</strong> — Test Guide, Test-Kreditkarten, Fehlercodes und Paygate-Status sind auf der Hilfeseite mit passenden Inline-SVGs gekennzeichnet',
  ]}, en: { title: 'REST Request Builder', items: [
    '<strong>One payment workflow</strong> — Classic Paygate and REST API can be selected inside the existing Payment Workflow',
    '<strong>REST V1 and V2</strong> — Hosted Payment Page, Card Form and Pay By Link generate version-specific JSON requests and endpoints',
    '<strong>Correct V2 schema</strong> — Checkout sessions, hosted card payments and payment links use fields such as <code>transId</code>, string descriptions and <code>Idempotency-Key</code>',
    '<strong>Environments & auth</strong> — Production and test servers plus Basic Auth and OAuth2 Client Credentials are selectable',
    '<strong>External execution</strong> — cURL, PowerShell, Postman Collection v2.1 and raw HTTP output include tailored guidance',
    '<strong>Syntax highlighting</strong> — The JSON payload and executable request are highlighted for the selected format',
    '<strong>Test-card guidance</strong> — Official test data is linked while card data remains outside the generated REST payload',
    '<strong>Secure defaults</strong> — The browser sends no REST request and uses credential placeholders by default',
    '<strong>Explicit opt-in</strong> — Merchant ID and REST API key are only inserted into output after explicit selection',
    '<strong>Local profiles</strong> — The REST API key can be encrypted together with the existing credentials',
    '<strong>Clear ownership</strong> — The Classic GET URL explanation only appears in the Classic flow; navigation badges identify Payment Workflow and Classic features',
    '<strong>REST feature pills</strong> — REST API V1/V2, JSON Builder plus cURL, PowerShell and Postman appear as additional features below the main title',
    '<strong>Clean labels</strong> — REST version wording was simplified and visible product naming was standardised to Paygate',
    '<strong>Release metadata</strong> — Footer, app metadata, PWA cache and documentation were updated to version 3.0.0',
    '<strong>Stable workflow navigation</strong> — Active-step detection follows a fixed line below the navbar and remains consistent after navigation clicks; collapsed cards no longer show an internal divider',
    '<strong>Preview empty state</strong> — Switching between Classic and REST now reliably restores a bilingual waiting message in Step 3 instead of leaving an empty card',
    '<strong>Desktop navigation</strong> — Glass arrow controls now appear automatically at the navbar edges when space is limited, with horizontal mouse-wheel scrolling as an additional option',
    '<strong>Help page</strong> — A new bilingual navbar view combines integration guidance, app instructions, official documentation, test data, error codes and privacy notes',
    '<strong>Guide badge</strong> — Help is identified in the navbar by its own violet Guide badge',
    '<strong>Persistent badge colours</strong> — Payment Workflow, Classic and Guide retain their green, blue and violet group colours while their navigation item is active',
    '<strong>Consistent waiting notice</strong> — The Step 3 empty state now uses the standard inline information style with a clean icon-and-text baseline',
    '<strong>Resource icons</strong> — Test Guide, test cards, error codes and Paygate status use matching inline SVG icons on the Help page',
  ]}},
  { v: 'v2.9.0', de: { title: 'PWA-Zahlungsrückkehr', items: [
    '<strong>Rückgabe an die PWA</strong> — Der externe Paygate-Tab überträgt den Callback an eine bereits geöffnete installierte App',
    '<strong>Sicherer Zahlungs-Tab</strong> — <code>noopener</code> bleibt aktiv; die Übergabe erfolgt über BroadcastChannel mit Storage-Fallback',
    '<strong>Bestätigtes Schließen</strong> — Der Callback-Tab schließt sich erst, nachdem die PWA den Response übernommen hat',
    '<strong>Launch Handler</strong> — Manifest-Hinweise erlauben unterstützten Browsern, ein vorhandenes App-Fenster wiederzuverwenden',
    '<strong>Einheitliche Seitenköpfe</strong> — Das Glass-Schild erscheint nun auch auf Request-Log, Response-Ansichten und Changelog',
    '<strong>Aktualisierter Footer</strong> — Die kompakte GitHub-Adresse ist sichtbar und das Paygate-Dokumentationsziel wurde erneuert',
  ]}, en: { title: 'PWA Payment Return', items: [
    '<strong>Return to the PWA</strong> — The external Paygate tab transfers the callback to an already open installed app',
    '<strong>Secure payment tab</strong> — <code>noopener</code> remains enabled; transfer uses BroadcastChannel with a storage fallback',
    '<strong>Confirmed closing</strong> — The callback tab only closes after the PWA has accepted the response',
    '<strong>Launch handler</strong> — Manifest hints let supported browsers reuse an existing app window',
    '<strong>Consistent page headers</strong> — The glass shield now also appears on request log, response and changelog views',
    '<strong>Updated footer</strong> — The compact GitHub address is visible and the Paygate documentation target has been updated',
  ]}},
  { v: 'v2.8.0', de: { title: 'Einleitung auf der Hauptseite', items: [
    '<strong>Klare Einführung</strong> — Ein kurzer zweisprachiger Text erklärt Zweck und Zielgruppe des Paygate Payment Testers',
    '<strong>Drei Kernbereiche</strong> — Request-Erstellung, Verschlüsselungsprüfung und Response-Analyse werden kompakt beschrieben',
    '<strong>Lokale Verarbeitung</strong> — Ein eigener Hinweis erklärt den Betrieb ohne Installation und ohne dediziertes Backend',
    '<strong>Responsive Glass-Karte</strong> — Die Einleitung fügt sich in das Design ein und stapelt ihre Inhalte auf kleinen Displays',
  ]}, en: { title: 'Main Page Introduction', items: [
    '<strong>Clear introduction</strong> — A concise bilingual text explains the purpose and audience of the Paygate Payment Tester',
    '<strong>Three core areas</strong> — Request creation, encryption inspection and response analysis are summarised clearly',
    '<strong>Local processing</strong> — A dedicated note explains operation without installation or a dedicated backend',
    '<strong>Responsive glass card</strong> — The introduction matches the design and stacks its content on small screens',
  ]}},
  { v: 'v2.7.9', de: { title: 'Einheitliche Seitenüberschriften', items: [
    '<strong>Keine 56px-Sondergröße</strong> — Die abweichende Überschriftengröße der separaten Ansichten wurde entfernt',
    '<strong>Maximal 44px</strong> — Alle Seitentitel verwenden nun exakt dieselbe Skala wie Paygate Payment Tester',
    '<strong>Mobile Einheitlichkeit</strong> — Skalierung und Titelabstand stimmen auch auf kleinen Bildschirmen überein',
  ]}, en: { title: 'Unified Page Headings', items: [
    '<strong>No 56px override</strong> — Removed the separate heading size used by standalone views',
    '<strong>44px maximum</strong> — Every page title now uses the exact same scale as Paygate Payment Tester',
    '<strong>Mobile consistency</strong> — Scaling and title spacing also match on small screens',
  ]}},
  { v: 'v2.7.8', de: { title: 'Feinschliff der Inline-Ausrichtung', items: [
    '<strong>Hinweiszeilen</strong> — Text und Info-Icon teilen sich jetzt eine saubere gemeinsame Grundlinie',
    '<strong>Paygate-Badge</strong> — Punkt, Schild und Schrift sind innerhalb der Blase exakt vertikal zentriert',
    '<strong>Beide Ansichten</strong> — Die Korrektur gilt für Payment Workflow und Response-Entschlüsselung',
  ]}, en: { title: 'Inline Alignment Polish', items: [
    '<strong>Information rows</strong> — Label text and information icon now share a clean common baseline',
    '<strong>Paygate badge</strong> — Dot, shield and text are vertically centered within the pill',
    '<strong>Both views</strong> — Applied the correction to Payment Workflow and Response Decryption',
  ]}},
  { v: 'v2.7.7', de: { title: 'Glass-Header-Icon & Feature-Pills', items: [
    '<strong>Transparentes Logo</strong> — Die Schildkachel verwendet jetzt eine halbtransparente Glass-Fläche mit Hintergrund-Blur',
    '<strong>Dark & Light Mode</strong> — Eigene Farbabstimmungen halten das Schild in beiden Modi deutlich sichtbar',
    '<strong>Feature-Pills</strong> — Die bisherige Punktliste wurde durch fünf kompakte, responsive Blasen ersetzt',
    '<strong>Übersetzbar</strong> — Jede Feature-Bezeichnung wird weiterhin einzeln auf Deutsch und Englisch ausgegeben',
  ]}, en: { title: 'Glass Header Icon & Feature Pills', items: [
    '<strong>Translucent logo</strong> — The shield tile now uses a translucent glass surface with backdrop blur',
    '<strong>Dark & light mode</strong> — Dedicated color treatments keep the shield clear in both appearances',
    '<strong>Feature pills</strong> — Replaced the dot-separated list with five compact responsive bubbles',
    '<strong>Translatable</strong> — Every feature label remains individually available in German and English',
  ]}},
  { v: 'v2.7.6', de: { title: 'Kompakte Navigation ohne Trennlinien', items: [
    '<strong>Schmale Ansichten</strong> — Unnötige Gruppentrenner wurden aus der horizontal scrollbaren Navbar entfernt',
    '<strong>Desktop</strong> — Die dezente Gruppierung der vollständig sichtbaren Navigation bleibt erhalten',
  ]}, en: { title: 'Compact Navigation Without Separators', items: [
    '<strong>Narrow layouts</strong> — Removed unnecessary group separators from the horizontally scrollable navigation',
    '<strong>Desktop</strong> — Preserved the subtle grouping of the fully visible navigation',
  ]}},
  { v: 'v2.7.5', de: { title: 'Schwebender Glass-Footer', items: [
    '<strong>Identische Breite</strong> — Der Footer verwendet nun dieselbe maximale Breite von 1400px wie die Glass-Navigation',
    '<strong>Vollständige Rundung</strong> — Eine umlaufende Glaskante und 18px-Radius formen eine schwebende Kapsel',
    '<strong>Abstand zum Rand</strong> — Der Footer schwebt mit gleichmäßiger Außenluft über dem unteren Fensterrand',
    '<strong>Mobile Darstellung</strong> — Auf kleinen Displays entsprechen Seitenabstand und 15px-Radius ebenfalls der Navbar',
  ]}, en: { title: 'Floating Glass Footer', items: [
    '<strong>Matching width</strong> — The footer now uses the same 1400px maximum width as the glass navigation',
    '<strong>Complete rounding</strong> — A full glass border and 18px radius create a floating capsule',
    '<strong>Viewport spacing</strong> — Balanced outer space lifts the footer above the bottom edge',
    '<strong>Mobile presentation</strong> — Small screens also match the navigation’s side spacing and 15px radius',
  ]}},
  { v: 'v2.7.4', de: { title: 'Glass-Footer', items: [
    '<strong>Einheitliches Glass-Design</strong> — Der Footer verwendet nun denselben halbtransparenten Hintergrund wie die Navigation',
    '<strong>Mehr Tiefe</strong> — Blur, Sättigung, transparente Kante und dezentes Innenlicht machen den Hintergrund sichtbar',
    '<strong>Dark & Light Mode</strong> — Abgestimmte Schatten sorgen in beiden Darstellungen für eine klare Abgrenzung',
  ]}, en: { title: 'Glass Footer', items: [
    '<strong>Consistent glass design</strong> — The footer now uses the same translucent background treatment as the navigation',
    '<strong>More depth</strong> — Blur, saturation, a translucent edge and subtle inner highlight reveal the background beneath it',
    '<strong>Dark & light mode</strong> — Balanced shadows provide clear separation in both appearances',
  ]}},
  { v: 'v2.7.3', de: { title: 'Einheitliche Ansichtstypografie', items: [
    '<strong>Seitentitel</strong> — Werkzeugansichten verwenden nun ausdrücklich dieselbe Schriftstärke, Laufweite und Zeilenhöhe wie der Payment Workflow',
    '<strong>Untertitel</strong> — Schriftfamilie, Größe, Gewicht und Zeichenabstand sind in allen Ansichten angeglichen',
    '<strong>Klare Hierarchie</strong> — Die Werkzeugtitel bleiben bewusst größer als der Titel des Payment Workflows',
  ]}, en: { title: 'Consistent View Typography', items: [
    '<strong>Page titles</strong> — Tool views now explicitly use the same font weight, letter spacing and line height as the Payment Workflow',
    '<strong>Subtitles</strong> — Font family, size, weight and character spacing now match across all views',
    '<strong>Clear hierarchy</strong> — Tool titles intentionally remain larger than the Payment Workflow title',
  ]}},
  { v: 'v2.7.2', de: { title: 'Social-Metadaten & SEO', items: [
    '<strong>Open Graph</strong> — Locale, sichere Bild-URL, PNG-Typ und englischer Alt-Text sind vollständig hinterlegt',
    '<strong>Konsistente Vorschau</strong> — Seiten-, Twitter-, Manifest- und Social-Beschreibungen passen nun zum englischen OG-Bild',
    '<strong>Crawler-Steuerung</strong> — Große Bildvorschauen und vollständige Snippets sind ausdrücklich erlaubt',
    '<strong>Strukturierte Daten</strong> — SoftwareApplication-Daten beschreiben App, Version, Lizenz und Repository',
  ]}, en: { title: 'Social Metadata & SEO', items: [
    '<strong>Open Graph</strong> — Added locale, secure image URL, PNG type and English alternative text',
    '<strong>Consistent preview</strong> — Page, Twitter, manifest and social descriptions now match the English OG image',
    '<strong>Crawler controls</strong> — Explicitly enables large image previews and complete snippets',
    '<strong>Structured data</strong> — SoftwareApplication data describes the app, version, license and repository',
  ]}},
  { v: 'v2.7.1', de: { title: 'Social-Media-Vorschaubild', items: [
    '<strong>Open-Graph-Bild</strong> — Neue 1200×630-Vorschau im Glass-Design der App',
    '<strong>App-Branding</strong> — Schildlogo, Integrationsmethoden und Sicherheitsfunktionen stehen im Mittelpunkt',
    '<strong>Link-Vorschauen</strong> — Open Graph, Twitter Card, Canonical URL und Seitenbeschreibung sind vollständig hinterlegt',
    '<strong>Offline-Cache</strong> — Das Vorschaubild wird gemeinsam mit den übrigen App-Ressourcen gespeichert',
  ]}, en: { title: 'Social Sharing Preview', items: [
    '<strong>Open Graph image</strong> — New 1200×630 preview matching the app’s glass design',
    '<strong>App branding</strong> — Highlights the shield logo, integration methods and security features',
    '<strong>Link previews</strong> — Includes complete Open Graph, Twitter Card, canonical URL and page description metadata',
    '<strong>Offline cache</strong> — The preview image is cached with the other application assets',
  ]}},
  { v: 'v2.7.0', de: { title: 'IndexedDB-Logs & Syntax-Highlighting', items: [
    '<strong>IndexedDB-Speicherung</strong> — Request- und Response-Logs liegen in getrennten lokalen Objektspeichern',
    '<strong>Automatische Migration</strong> — Vorhandene localStorage-Logs werden beim ersten Start vollständig übernommen',
    '<strong>Lokaler Fallback</strong> — Falls IndexedDB nicht verfügbar ist, arbeitet die App weiterhin mit localStorage',
    '<strong>Mehr Historie</strong> — Beide Logs speichern jetzt bis zu 250 statt 50 Einträge',
    '<strong>Syntax-Highlighting</strong> — Endpunkte, Parameternamen, verschlüsselte Werte, Längen und Statuswerte sind farblich unterscheidbar',
    '<strong>Sprachabhängige Zeitangaben</strong> — Log-Zeitstempel folgen der ausgewählten deutschen oder englischen Sprache',
    '<strong>Alle Daten löschen</strong> — Leert nun zusätzlich beide IndexedDB-Logspeicher',
  ]}, en: { title: 'IndexedDB Logs & Syntax Highlighting', items: [
    '<strong>IndexedDB storage</strong> — Request and response logs use separate local object stores',
    '<strong>Automatic migration</strong> — Existing localStorage logs are fully imported on first launch',
    '<strong>Local fallback</strong> — The app continues to use localStorage when IndexedDB is unavailable',
    '<strong>More history</strong> — Both logs now retain up to 250 entries instead of 50',
    '<strong>Syntax highlighting</strong> — Endpoints, parameter names, encrypted values, lengths and statuses are visually distinct',
    '<strong>Localized timestamps</strong> — Log timestamps follow the selected German or English language',
    '<strong>Clear all data</strong> — Now also clears both IndexedDB log stores',
  ]}},
  { v: 'v2.6.1', de: { title: 'Eindeutige Pay-by-Link-Referenzen', items: [
    '<strong>Automatische RefNr</strong> — Beim Auswählen von Pay By Link wird automatisch eine Referenznummer erzeugt',
    '<strong>Kryptografischer Zufall</strong> — Die Referenz verwendet sichere Zufallswerte und bleibt unter dem 30-Zeichen-Limit des Paygate',
    '<strong>Kein lokales Wiederverwenden</strong> — Bis zu 5.000 bereits verwendete Referenzen werden im Browser registriert',
    '<strong>Neue Vorschau, neue RefNr</strong> — Jede weitere Pay-by-Link-Vorschau erhält automatisch eine frische Referenz',
    '<strong>Manuelle Erneuerung</strong> — Ein Button erzeugt bei Bedarf bereits vor der Vorschau eine neue Referenz',
    '<strong>Alle Daten löschen</strong> — Entfernt auch die lokale Liste verwendeter Referenzen',
  ]}, en: { title: 'Unique Pay By Link References', items: [
    '<strong>Automatic RefNr</strong> — Selecting Pay By Link automatically generates a reference number',
    '<strong>Cryptographic randomness</strong> — The reference uses secure random values and remains below Paygate’s 30-character limit',
    '<strong>No local reuse</strong> — Up to 5,000 previously used references are registered in the browser',
    '<strong>New preview, new RefNr</strong> — Every subsequent Pay By Link preview automatically receives a fresh reference',
    '<strong>Manual regeneration</strong> — A button can create a new reference before generating the preview',
    '<strong>Clear all data</strong> — Also removes the local registry of used references',
  ]}},
  { v: 'v2.6.0', de: { title: 'Touch- & Mobile-Layout', items: [
    '<strong>Safe Areas</strong> — iPhone- und iPad-Aussparungen werden mit viewport-fit und Umgebungsabständen berücksichtigt',
    '<strong>Mobile Navbar</strong> — Die Navigation scrollt träge horizontal, statt Texte und Touchflächen unbrauchbar zu verkleinern',
    '<strong>44px-Touchziele</strong> — Navigation und wichtige Bedienelemente erfüllen auf Touchgeräten Apples empfohlene Mindestgröße',
    '<strong>Aktiver Nav-Punkt</strong> — Der ausgewählte Eintrag wird beim Wechsel automatisch sichtbar zentriert',
    '<strong>Safari-Formulare</strong> — 16px-Schriftgröße verhindert unerwünschtes Zoomen beim Fokus auf Eingabefelder',
    '<strong>Kleine Displays</strong> — Profilaktionen und Workflow-Buttons umbrechen sinnvoll; breite Testtabellen werden horizontal scrollbar',
  ]}, en: { title: 'Touch & Mobile Layout', items: [
    '<strong>Safe areas</strong> — iPhone and iPad cutouts are respected through viewport-fit and environment insets',
    '<strong>Mobile navbar</strong> — Navigation uses inertial horizontal scrolling instead of shrinking text and touch areas below usable sizes',
    '<strong>44px targets</strong> — Navigation and key controls meet Apple’s recommended minimum on touch devices',
    '<strong>Active nav item</strong> — The selected item automatically scrolls into a visible centered position',
    '<strong>Safari forms</strong> — 16px controls prevent unwanted zoom when focusing fields',
    '<strong>Small displays</strong> — Profile actions and workflow buttons wrap cleanly, while wide test tables scroll horizontally',
  ]}},
  { v: 'v2.5.2', de: { title: 'Icon- & Header-Feinschliff', items: [
    '<strong>Exakte Flux-Struktur</strong> — Der Icon-Ordner entspricht mit acht Dateien vollständig dem bewährten Aufbau von Flux Todo',
    '<strong>Saubere Kanten</strong> — Alle PNGs werden mit achtfachem Oversampling und Lanczos-Downsampling geglättet',
    '<strong>Optische Zentrierung</strong> — Schild und Check besitzen ausgeglichene obere und untere Abstände',
    '<strong>Getrennte Quellen</strong> — Eigene SVGs für App-Icon, abgerundetes Browser-Icon und Maskable-Icon',
    '<strong>Header-Icon</strong> — Das Schild steht als auflösungsunabhängiges Inline-SVG links neben dem Payment-Tester-Titel',
    '<strong>Responsive Darstellung</strong> — Das Header-Icon wird auf kleinen Bildschirmen kompakter dargestellt',
    '<strong>Dark Mode</strong> — Der störende farbige Außenschimmer um das Header-Icon wurde entfernt',
  ]}, en: { title: 'Icon & Header Polish', items: [
    '<strong>Exact Flux structure</strong> — The icon directory now fully matches Flux Todo’s proven eight-file layout',
    '<strong>Smooth edges</strong> — All PNGs use 8x oversampling and Lanczos downsampling for clean antialiasing',
    '<strong>Optical centering</strong> — Shield and check mark have balanced top and bottom spacing',
    '<strong>Separate sources</strong> — Dedicated SVGs for the app icon, rounded browser icon and maskable icon',
    '<strong>Header icon</strong> — The shield appears as a resolution-independent inline SVG to the left of the Paygate Payment Tester title',
    '<strong>Responsive presentation</strong> — The header icon becomes more compact on smaller screens',
    '<strong>Dark mode</strong> — Removed the distracting colored outer glow around the header icon',
  ]}},
  { v: 'v2.5.1', de: { title: 'iOS-App-Icon', items: [
    '<strong>Neues Icon</strong> — Reduziertes blau-weißes Schild im bewährten Stil der Flux-PWA',
    '<strong>Apple Touch Icon</strong> — Eigene deckende 180×180-PNG für die Installation auf dem iOS-Homescreen',
    '<strong>PWA-Varianten</strong> — Standard- und maskierbare Icons in 192×192 und 512×512',
    '<strong>Systemdarstellung</strong> — Keine vorgerenderten Glas- oder Rundungseffekte, damit iOS Dark, Tinted und Clear selbst anwenden kann',
    '<strong>Flux-Struktur</strong> — Exakt acht Dateien mit getrennten App-, Browser- und Maskable-Quellen',
  ]}, en: { title: 'iOS App Icon', items: [
    '<strong>New icon</strong> — Minimal blue-and-white shield following the proven Flux PWA style',
    '<strong>Apple Touch Icon</strong> — Dedicated opaque 180×180 PNG for iOS Home Screen installation',
    '<strong>PWA variants</strong> — Standard and maskable icons at 192×192 and 512×512',
    '<strong>System appearance</strong> — No pre-rendered glass or corner effects, allowing iOS to apply Dark, Tinted and Clear treatments',
    '<strong>Flux structure</strong> — Exactly eight files with separate app, browser and maskable sources',
  ]}},
  { v: 'v2.5.0', de: { title: 'Pay By Link', items: [
    '<strong>Dritte Integrationsmethode</strong> — Pay By Link kann in Schritt 2 neben Hosted Payment Page und Kreditkartenformular gewählt werden',
    '<strong>Pflichtfelder</strong> — RefNr und ExpirationDate werden validiert; das Ablaufdatum ist standardmäßig sieben Tage in der Zukunft',
    '<strong>Doppelte Verschlüsselung</strong> — Innerer HPP-Payload und äußerer Pay-By-Link-Payload werden gemäß Paygate-Dokumentation nacheinander mit Blowfish ECB verschlüsselt',
    '<strong>Transparente Vorschau</strong> — Beide Payload-Ebenen, Query-Parameter und die vollständige action=create-URL können geprüft und kopiert werden',
    '<strong>Browser-Hinweis</strong> — Die Oberfläche weist auf die dokumentierte Server-zu-Server-Nutzung und mögliche CORS-Einschränkungen hin',
    '<strong>Regressionstest</strong> — Beide Verschlüsselungsebenen werden entschlüsselt und strukturell geprüft',
  ]}, en: { title: 'Pay By Link', items: [
    '<strong>Third integration method</strong> — Pay By Link is available in Step 2 alongside Hosted Payment Page and Credit Card Form',
    '<strong>Required fields</strong> — RefNr and ExpirationDate are validated, with expiration defaulting to seven days from now',
    '<strong>Double encryption</strong> — The inner HPP payload and outer Pay By Link payload are encrypted sequentially with Blowfish ECB as documented for Paygate',
    '<strong>Transparent preview</strong> — Both payload layers, query parameters and the complete action=create URL can be inspected and copied',
    '<strong>Browser notice</strong> — The UI explains the documented server-to-server usage and possible CORS restrictions',
    '<strong>Regression test</strong> — Both encryption layers are decrypted and structurally verified',
  ]}},
  { v: 'v2.4.0', de: { title: 'App-Shell & Glass-UI', items: [
    '<strong>Eigene App-Ansichten</strong> — Payment Workflow, Request-Log, Response-Entschlüsselung, Response-Log und Changelog besitzen eigene Ansichten',
    '<strong>Persistente App-Hülle</strong> — Glass-Navbar und gemeinsamer Footer bleiben in jeder Ansicht sichtbar',
    '<strong>Hash-Routing</strong> — Direkte Links sowie Browser-Zurück und -Vorwärts funktionieren für alle Ansichten',
    '<strong>Payment Workflow</strong> — Credentials, Zahlungsparameter und Vorschau bleiben in einem durchgängigen Ablauf zusammen',
    '<strong>App-Dialog</strong> — „Alle Daten löschen“ verwendet einen zweisprachigen In-App-Dialog statt der nativen Browserwarnung',
    '<strong>Neuer Hintergrund</strong> — Farbige Lichtflächen, Raster und transparente Karten machen die Glass-Effekte deutlich sichtbar',
    '<strong>Einheitliches Layout</strong> — Inhaltsansichten und Footer verwenden dieselbe Breite',
    '<strong>Dokumentation</strong> — README beschreibt Architektur, Ansichten, lokale Nutzung, Sicherheit und Tests neu',
  ]}, en: { title: 'App Shell & Glass UI', items: [
    '<strong>Dedicated app views</strong> — Payment Workflow, Request Log, Response Decryption, Response Log and Changelog have their own views',
    '<strong>Persistent app shell</strong> — The glass navbar and shared footer remain visible in every view',
    '<strong>Hash routing</strong> — Direct links and browser Back/Forward work across all views',
    '<strong>Payment Workflow</strong> — Credentials, payment parameters and preview remain together in one continuous flow',
    '<strong>App dialog</strong> — “Delete all data” uses a bilingual in-app dialog instead of the native browser warning',
    '<strong>New background</strong> — Colored light fields, the grid and translucent cards make the glass effects clearly visible',
    '<strong>Consistent layout</strong> — Content views and the footer use the same width',
    '<strong>Documentation</strong> — The README now describes the architecture, views, local usage, security and tests',
  ]}},
  { v: 'v2.3.0', de: { title: 'Glass-Navigation', items: [
    '<strong>Neue Glass-Navbar</strong> — Fixierte Navigation mit Backdrop-Blur, durch die der Seiteninhalt sichtbar hindurchscrollt',
    '<strong>Drei Bereiche</strong> — Zahlungsschritte links, Logs und Entschlüsselung mittig, Changelog sowie Sprach- und Theme-Steuerung rechts',
    '<strong>Intelligente Navigation</strong> — Der sichtbare Workflow-Abschnitt wird hervorgehoben',
    '<strong>Responsive</strong> — Auf kleineren Bildschirmen bleibt die vollständige Navigation horizontal scrollbar',
  ]}, en: { title: 'Glass Navigation', items: [
    '<strong>New glass navbar</strong> — Fixed navigation with backdrop blur while page content visibly scrolls underneath',
    '<strong>Three zones</strong> — Payment steps on the left, logs and decryption in the center, changelog plus language and theme controls on the right',
    '<strong>Smart navigation</strong> — The visible workflow section is highlighted',
    '<strong>Responsive</strong> — The complete navigation remains horizontally scrollable on smaller screens',
  ]}},
  { v: 'v2.2.4', de: { title: 'Sicherheit & Wartbarkeit', items: [
    '<strong>Sichere DOM-Ausgabe</strong> — Dynamische Request-, Callback-, Profil- und Log-Werte werden als Text statt als HTML gerendert',
    '<strong>Crypto-Regressionstests</strong> — HMAC-SHA256, Len und Blowfish-Data werden gegen einen festen Referenzvektor geprüft',
    '<strong>Saubere Versionierung</strong> — Zentrale VERSION-Datei und Konsistenztest für App, README, Service Worker und Changelog',
    '<strong>Dateiaufteilung</strong> — Übersetzungen und Changelog-Daten wurden ausgelagert; die App bleibt direkt über file:// nutzbar',
  ]}, en: { title: 'Security & Maintainability', items: [
    '<strong>Safe DOM rendering</strong> — Dynamic request, callback, profile and log values are rendered as text instead of HTML',
    '<strong>Crypto regression tests</strong> — HMAC-SHA256, Len and Blowfish Data are checked against a fixed reference vector',
    '<strong>Consistent versioning</strong> — Central VERSION file and consistency checks for the app, README, service worker and changelog',
    '<strong>File separation</strong> — Translations and changelog data were extracted while preserving direct file:// usage',
  ]}},
{ v: 'v2.2.3', de: { title: 'PWA-Support & Favicon', items: [
    '<strong>Progressive Web App</strong> — Die App kann jetzt als eigenständige Webapp auf allen Geräten installiert werden (Chrome, Edge, Safari)',
    '<strong>Favicon</strong> — Neues Schild-Icon mit Checkmark als Favicon im Browser-Tab (inline Data-URI)',
    '<strong>Service Worker</strong> — Network-First-Caching für Offline-Nutzung der App',
    '<strong>Web App Manifest</strong> — Manifest für App-Name, Icon und Standalone-Modus',
  ]}, en: { title: 'PWA Support & Favicon', items: [
    '<strong>Progressive Web App</strong> — the app can now be installed as a standalone webapp on all devices (Chrome, Edge, Safari)',
    '<strong>Favicon</strong> — new shield icon with checkmark as browser tab favicon (inline data URI)',
    '<strong>Service Worker</strong> — network-first caching for offline usage of the app',
    '<strong>Web App Manifest</strong> — manifest for app name, icon, and standalone mode',
  ]}},
  { v: 'v2.2.2', de: { title: 'UX-Verbesserungen & Changelog-Übersetzung', items: [
    '<strong>Changelog zweisprachig</strong> — Changelog wird jetzt dynamisch gerendert und wechselt beim Sprachwechsel komplett zwischen Deutsch und Englisch',
    '<strong>Buttons verschoben</strong> — „Vorschau generieren" und „Neue Trans-ID" von Schritt 3 nach Schritt 2 verschoben, wo die Parameter konfiguriert werden',
    '<strong>Testkarten verschoben</strong> — Testkartentabellen (Non-3DS & 3-D Secure 2.x) von Schritt 2 nach Schritt 3 verschoben, direkt über dem Submit-Button',
    '<strong>Schritt 3 zugeklappt</strong> — Box ist beim ersten Besuch zugeklappt mit Hinweistext; klappt automatisch auf nach Vorschau-Generierung',
    'Button-Höhen vereinheitlicht — Inline-Style beim Submit-Button entfernt',
  ]}, en: { title: 'UX Improvements & Changelog Translation', items: [
    '<strong>Bilingual changelog</strong> — changelog is now dynamically rendered and fully switches between German and English when changing the language',
    '<strong>Buttons moved</strong> — "Generate Preview" and "New Trans-ID" moved from Step 3 to Step 2, where parameters are configured',
    '<strong>Test cards moved</strong> — test card tables (Non-3DS & 3-D Secure 2.x) moved from Step 2 to Step 3, right above the submit button',
    '<strong>Step 3 collapsed</strong> — box is collapsed on first visit with a hint message; auto-expands after preview generation',
    'Button heights unified — removed inline style override on the submit button',
  ]}},
  { v: 'v2.2', de: { title: 'PaySSL Template-Support & URL-Parameter-Übersicht', items: [
    '<strong>Template für payssl.aspx</strong> — Template-Parameter wird jetzt auch beim Kreditkartenformular (<code>payssl.aspx</code>) unterstützt; bei PaySSL wird der Parameter verschlüsselt im Data-String übergeben, bei HPP weiterhin unverschlüsselt als URL-Parameter',
    '<strong>URL-Parameter-Box</strong> — neue Übersicht in Schritt 3 zeigt alle unverschlüsselten Query-Parameter (<code>MerchantID</code>, <code>Len</code>, <code>Data</code>, <code>Language</code>, <code>URLBack</code>, <code>Template</code>) auf einen Blick',
    'Erster Debug-Block umbenannt in „Verschlüsselte Parameter (Data-String)" zur klareren Abgrenzung',
  ]}, en: { title: 'PaySSL Template Support & URL Parameter Overview', items: [
    '<strong>Template for payssl.aspx</strong> — the Template parameter is now supported for the credit card form (<code>payssl.aspx</code>) as well; for PaySSL the parameter is passed encrypted inside the Data string, for HPP it remains unencrypted as a URL parameter',
    '<strong>URL parameter box</strong> — new overview in Step 3 displays all unencrypted query-string parameters (<code>MerchantID</code>, <code>Len</code>, <code>Data</code>, <code>Language</code>, <code>URLBack</code>, <code>Template</code>) at a glance',
    'First debug block renamed to "Encrypted Parameters (Data String)" for clearer distinction',
  ]}},
  { v: 'v2.1.1', de: { title: 'Template-Parameter', items: [
    '<strong>Template-Parameter</strong> — neues Dropdown in den Erweiterten Einstellungen zum Steuern des Layouts der Zahlungsseite; Optionen: <code>ct_paymentpagelogos_v1</code>, <code>ct_paymentpagedropdown_v1</code>, <code>ct_paymentpagedropdown_v2</code> oder leer (Standard)',
    'Template wird unverschlüsselt an die URL angehängt, nur für <code>paymentPage.aspx</code> (HPP)',
  ]}, en: { title: 'Template Parameter', items: [
    '<strong>Template parameter</strong> — new dropdown in Advanced Settings to control the payment page layout; options: <code>ct_paymentpagelogos_v1</code>, <code>ct_paymentpagedropdown_v1</code>, <code>ct_paymentpagedropdown_v2</code> or empty (default)',
    'Template is appended unencrypted to the URL, only for <code>paymentPage.aspx</code> (HPP)',
  ]}},
  { v: 'v2.1', de: { title: 'Response-Log & Callback-Verbesserungen', items: [
    '<strong>Response-Log</strong> — speichert die letzten 50 entschlüsselten Responses im Browser; aufklappbare Einträge mit Status-Badge (OK/FAILED), TransID, MerchantID und kopierbarem Payload',
    '<strong>„Aktuell"-Badge</strong> — kennzeichnet die zuletzt entschlüsselte Response im Ergebnisbereich',
    '<strong>Auto-Aufklappen</strong> — Response-Entschlüsseler klappt bei Callback-Redirect automatisch auf',
    '<strong>OrderDesc-Default</strong> geändert auf <code>Test:0000</code> (Simulation: Erfolg)',
    'Profilname wird beim Laden eines Profils nicht mehr ins Namensfeld geschrieben',
    'Bugfix Callback-Receiver: <code>:has()</code>-Selektor durch kompatibles <code>.closest()</code> ersetzt; Timing-Problem bei der Auto-Entschlüsselung behoben; <code>checkCallbackParams()</code> in try-catch eingefasst',
    '„Alles löschen" löscht jetzt auch den Response-Log',
  ]}, en: { title: 'Response Log & Callback Improvements', items: [
    '<strong>Response log</strong> — stores the last 50 decrypted responses in the browser; expandable entries with status badge (OK/FAILED), TransID, MerchantID and copyable payload',
    '<strong>"Current" badge</strong> — marks the most recently decrypted response in the result area',
    '<strong>Auto-expand</strong> — the Response Decryptor card automatically opens on callback redirect',
    '<strong>OrderDesc default</strong> changed to <code>Test:0000</code> (Simulation: success)',
    'Profile name is no longer written back into the name field when loading a profile',
    'Bugfix callback receiver: replaced <code>:has()</code> selector with compatible <code>.closest()</code>; fixed timing issue on auto-decrypt; wrapped <code>checkCallbackParams()</code> in try-catch',
    '"Clear all data" now also clears the response log',
  ]}},
  { v: 'v2.0.5', de: { title: 'Callback-Empfänger & UX-Verbesserungen', items: [
    '<strong>Callback-Empfänger</strong> — Toggle in den Redirect-URLs setzt URLSuccess, URLFailure und URLBack auf diese Seite; bei Rückkehr vom Paygate wird die Antwort automatisch entschlüsselt — kein externer Dienst mehr nötig',
    '<strong>Mehrere Credential-Profile</strong> — benannte, verschlüsselte Profile mit Dropdown-Wähler; Migration vom alten Einzelprofil automatisch',
    '<strong>Alles löschen</strong> — Button im Footer entfernt alle gespeicherten Daten (Profile, Log, Einstellungen) auf einmal',
    '<strong>Profil-Name-Feld</strong> wird nach dem Speichern automatisch geleert',
    '<strong>Laden-Icon</strong> korrigiert — Pfeil zeigt nun nach oben (Upload-Semantik)',
    'Seitenbeschreibung aktualisiert: HPP ausgeschrieben als <em>Hosted Payment Page</em>',
    'Environment-Selector entfernt — beide Optionen zeigten auf dieselbe URL',
    'Credential-Felder: 2-spaltig (MerchantID + Blowfish) + vollbreite HMAC-Zeile',
  ]}, en: { title: 'Callback Receiver & UX Improvements', items: [
    '<strong>Callback receiver</strong> — toggle in the Redirect URLs section sets URLSuccess, URLFailure and URLBack to the tool\'s own URL; on return from Paygate the response is auto-decrypted — no external service required',
    '<strong>Multiple credential profiles</strong> — named, AES-GCM encrypted profiles with a dropdown selector; automatic migration from the old single-credential storage',
    '<strong>Clear all data</strong> — button in the footer removes all stored data (profiles, request log, settings) in one step',
    '<strong>Profile name field</strong> is cleared automatically after saving',
    '<strong>Load icon</strong> corrected — arrow now points upward (upload semantics)',
    'Page subtitle updated: HPP spelled out as <em>Hosted Payment Page</em>',
    'Environment selector removed — both options pointed to the same URL',
    'Credential field layout: 2-column row (MerchantID + Blowfish) + full-width HMAC row',
  ]}},
  { v: 'v2.0', de: { title: 'Kreditkartenformular (payssl.aspx)', items: [
    '<strong>Integrationsmethoden-Wähler</strong> — Segmented Control in Schritt 2 zum Umschalten zwischen <em>Hosted Payment Page</em> (<code>paymentPage.aspx</code>) und <em>Kreditkartenformular</em> (<code>payssl.aspx</code>)',
    'Info-Box erklärt den Unterschied der gewählten Methode; Submit-Button-Text passt sich automatisch an',
    '<strong>Erweiterte Einstellungen</strong> blendet sich bei payssl.aspx aus — PayTypes wird dort nicht unterstützt',
  ]}, en: { title: 'Credit Card Form (payssl.aspx)', items: [
    '<strong>Integration method selector</strong> — segmented control in Step 2 to switch between <em>Hosted Payment Page</em> (<code>paymentPage.aspx</code>) and <em>Credit Card Form</em> (<code>payssl.aspx</code>)',
    'Info box explains the difference of the selected method; submit button text updates automatically',
    '<strong>Advanced Settings</strong> section hides when payssl.aspx is selected — PayTypes is not supported there',
  ]}},
  { v: 'v1.9.1', de: { title: 'Tooltip-Dokumentation & UX-Verbesserungen', items: [
    '<strong>Inline-Tooltips</strong> — <code>?</code>-Icon neben allen 15 Parametern mit kurzer Erklärung; viewport-aware positioniert (kein Abschneiden am Rand)',
    '<strong>Kartennummern formatiert</strong> — 3DS-2.x-Testkartennummern jetzt mit Leerzeichen wie die Non-3DS-Karten (z.B. <code>4000 0199 6619 9434</code>)',
    '<strong>Dokumentationslink</strong> — Link zur Paygate-Dokumentation in beiden Testkartentabellen (Non-3DS & 3DS) als Quellenangabe',
    '<strong>Template-Parameter entfernt</strong> — war nicht notwendig; bei gebuchter Corporate PaymentPage lädt das Paygate das Layout automatisch',
  ]}, en: { title: 'Tooltip Documentation & UX Improvements', items: [
    '<strong>Inline tooltips</strong> — <code>?</code> icon next to all 15 parameters with a short explanation; viewport-aware positioning (never clipped at the edge)',
    '<strong>Formatted card numbers</strong> — 3DS 2.x test card numbers now use spaces like the Non-3DS cards (e.g. <code>4000 0199 6619 9434</code>)',
    '<strong>Documentation link</strong> — link to the Paygate documentation added to both test card tables (Non-3DS & 3DS) as a source reference',
    '<strong>Template parameter removed</strong> — was unnecessary; if Corporate PaymentPage is booked, Paygate loads the layout automatically',
  ]}},
  { v: 'v1.9', de: { title: '3-D Secure Testkartennummern', items: [
    'Zweite Testkartentabelle <strong>(3-D Secure 2.x)</strong> in den Zahlungsparametern hinzugefügt',
    'Abgedeckte Szenarien: Frictionless – Authentifiziert, Challenge (OTP: <code>1234</code>), Nicht authentifiziert',
    'Karten für Visa, MasterCard und Amex — farbcodiert nach Szenario',
  ]}, en: { title: '3-D Secure Test Card Numbers', items: [
    'Added second test card table <strong>(3-D Secure 2.x)</strong> in the payment parameters section',
    'Scenarios covered: Frictionless – Authenticated, Challenge (OTP: <code>1234</code>), Not authenticated',
    'Cards for Visa, MasterCard and Amex — colour-coded by scenario',
  ]}},
  { v: 'v1.8.1', de: { title: 'Bugfix: MAC-Berechnung', items: [
    'MAC-String-Format korrigiert: <code>*TransID*MerchantID*Amount*Currency</code> — führendes <code>*</code> für leere PayID war bisher fehlend',
    'Ohne diesen Fix lehnte das Paygate jeden Request mit <strong>„MAC INVALID"</strong> ab',
    'Technische Erklärung im Credentials-Bereich entsprechend aktualisiert',
  ]}, en: { title: 'Bugfix: MAC Calculation', items: [
    'Fixed MAC string format: <code>*TransID*MerchantID*Amount*Currency</code> — the leading <code>*</code> for empty PayID was missing',
    'Without this fix Paygate rejected every request with <strong>"MAC INVALID"</strong>',
    'Updated the technical explainer in the Credentials section accordingly',
  ]}},
  { v: 'v1.8', de: { title: 'Testkartennummern & Simulationsmodi', items: [
    '<strong>OrderDesc als Dropdown</strong> — vorgefertigte Optionen für Erfolg (<code>Test:0000</code>), Ablehnung (<code>Test:0305</code>) und eigene Eingabe',
    '<strong>Testkartentabelle</strong> (Non-3DS) in den Zahlungsparametern — Visa, MasterCard, Amex jeweils mit Erfolg und Ablehnung',
    'Kartennummer per Klick in die Zwischenablage kopieren',
    'Tabelle und Dropdown vollständig übersetzt (DE / EN)',
  ]}, en: { title: 'Test Cards & Simulation Modes', items: [
    '<strong>OrderDesc dropdown</strong> with presets for success (<code>Test:0000</code>), decline (<code>Test:0305</code>) and custom input',
    '<strong>Test card table</strong> (Non-3DS) in the payment form — Visa, MasterCard, Amex with success and decline card numbers',
    'Card numbers are click-to-copy',
    'Table and dropdown fully translated (DE / EN)',
  ]}},
  { v: 'v1.7', de: { title: 'Response-Entschlüsseler', items: [
    'Neuer Bereich <strong>„Response-Entschlüsseler"</strong> — entschlüsselt Paygate-Callback-URLs direkt im Browser',
    'Vollständige Callback-URL einfügen: <code>MerchantID</code>, <code>Len</code> und <code>Data</code> werden automatisch extrahiert',
    'Alternativ <code>Data</code>-Hex und <code>Len</code> manuell eingeben',
    'Farbcodierte Darstellung der entschlüsselten Parameter — <code>Status</code> grün/rot/orange je nach Wert, <code>MAC</code> lila',
    'Blowfish-<code>decrypt</code>-Funktion zur bestehenden ECB-Implementierung hinzugefügt',
  ]}, en: { title: 'Response Decryptor', items: [
    'Added <strong>Response Decryptor</strong> section — decrypts Paygate callback URLs directly in the browser',
    'Paste the full callback URL: <code>MerchantID</code>, <code>Len</code> and <code>Data</code> are extracted automatically',
    'Alternative manual mode: enter <code>Data</code> (hex) and <code>Len</code> directly',
    'Color-coded output — <code>Status</code> green/red/orange by value, <code>MAC</code> purple',
    'Added Blowfish <code>decrypt</code> function alongside the existing ECB encrypt implementation',
  ]}},
  { v: 'v1.6', de: { title: 'Mehrsprachigkeit (DE / EN)', items: [
    '<strong>Sprach-Schalter</strong> im Header (neben dem Dark-/Light-Mode-Toggle): wechselt die gesamte Benutzeroberfläche zwischen Deutsch und Englisch',
    'Vollständige <strong>EN-Übersetzung</strong> aller UI-Texte — Labels, Buttons, Hinweise, Fehlermeldungen, Toasts und Bestätigungsdialoge',
    'Sprachpräferenz wird in <code>localStorage</code> gespeichert und beim nächsten Besuch automatisch wiederhergestellt',
    'i18n-System via <code>TRANSLATIONS</code>-Objekt und <code>t(key)</code>-Funktion — kein externes Framework nötig',
  ]}, en: { title: 'Multilingual UI (DE / EN)', items: [
    '<strong>Language toggle</strong> in the header (next to the theme toggle): switches the entire UI between German and English',
    'Full <strong>English translation</strong> of all UI text — labels, buttons, hints, error messages, toasts and confirmation dialogs',
    'Language preference saved in <code>localStorage</code> and restored automatically on the next visit',
    'Lightweight i18n system using a <code>TRANSLATIONS</code> object and a <code>t(key)</code> helper — no external framework',
  ]}},
  { v: 'v1.5', de: { title: 'Technische Erläuterung der URL-Generierung', items: [
    'Ausführliche <strong>3-Schritt-Erklärung</strong> im Credentials-Bereich hinzugefügt: MAC-Berechnung, Payload-Verschlüsselung und URL-Zusammensetzung',
    'Rolle des <strong>HMAC-Passworts</strong> erläutert — HMAC-SHA256-Signatur über <code>TransID * MerchantID * Amount * Currency</code> zur Sicherstellung der Anfrageintegrität',
    'Rolle des <strong>Blowfish-Passworts</strong> erläutert — ECB-Verschlüsselung des vollständigen Payloads inkl. MAC, hex-kodiert als <code>Data</code>-Parameter',
    'Visuelle <strong>URL-Anatomie</strong> mit farbcodierten Parametern (<code>MerchantID</code>, <code>Len</code>, <code>Data</code>) und Legende',
  ]}, en: { title: 'Technical Explanation of URL Generation', items: [
    'Added detailed <strong>3-step explanation</strong> in the Credentials section: MAC calculation, payload encryption and URL composition',
    'Role of the <strong>HMAC password</strong> explained — HMAC-SHA256 signature over <code>TransID * MerchantID * Amount * Currency</code> to ensure request integrity',
    'Role of the <strong>Blowfish password</strong> explained — ECB encryption of the full payload including MAC, hex-encoded as the <code>Data</code> parameter',
    'Visual <strong>URL anatomy</strong> with colour-coded parameters (<code>MerchantID</code>, <code>Len</code>, <code>Data</code>) and legend',
  ]}},
  { v: 'v1.4', de: { title: 'Security Disclaimer', items: [
    'Sicherheitshinweis zu produktiven Credentials direkt auf der Startseite hinzugefügt',
    'Nutzer wird explizit auf seine <strong>Eigenverantwortung</strong> beim Umgang mit API-Zugangsdaten hingewiesen',
    '<strong>Download-Button</strong> zur lokalen Ausführung der Seite — empfohlene Alternative zur öffentlichen URL',
  ]}, en: { title: 'Security Disclaimer', items: [
    'Security disclaimer regarding productive credentials added prominently to the start page',
    'User is explicitly informed of their <strong>responsibility</strong> for the safe handling of API credentials',
    '<strong>Download button</strong> for local execution — recommended alternative to using the public URL',
  ]}},
  { v: 'v1.3', de: { title: 'Zahlarten', items: [
    '<strong>„Alle freigeschalteten Zahlarten"</strong> als Standard — Weglassen des <code>PayTypes</code>-Parameters zeigt alle für den Merchant-Account konfigurierten Zahlarten an',
    'Bestehende Optionen <code>CC</code>, <code>VISA</code>, <code>MasterCard</code> und <code>AMEX</code> im Selector präzisiert',
  ]}, en: { title: 'Payment Methods', items: [
    'Added <strong>"All enabled payment methods"</strong> as the default — omitting the <code>PayTypes</code> parameter causes Paygate to display every method configured for the merchant account',
    'Clarified existing <code>CC</code>, <code>VISA</code>, <code>MasterCard</code> and <code>AMEX</code> options in the selector',
  ]}},
  { v: 'v1.2', de: { title: 'Icons', items: [
    'Alle Emoji durch <strong>professionelle inline SVGs</strong> (Lucide Icon Set) ersetzt',
    'Vollständig selbst-enthalten — kein CDN, funktioniert offline',
    'Spinning Loader-Animation auf dem Generieren-Button während der Verarbeitung',
  ]}, en: { title: 'Icons', items: [
    'Replaced all emoji with <strong>professional inline SVGs</strong> (Lucide icon set)',
    'Fully self-contained — no CDN required, works offline',
    'Spinning loader animation on the generate button while processing',
  ]}},
  { v: 'v1.1', de: { title: 'Dark / Light Mode', items: [
    '<strong>Dark/Light Mode Toggle</strong> (fixierter Button oben rechts)',
    '<strong>Auto-Modus</strong> folgt <code>prefers-color-scheme</code> und reagiert auf Live-Änderungen; zeigt <code>auto</code>-Badge',
    'Manuelle Präferenz wird in <code>localStorage</code> gespeichert und beim nächsten Besuch wiederhergestellt',
    'Flash-freier Load via Inline-Script im <code>&lt;head&gt;</code>',
    'Vollständige Light-Mode-Farbpalette mit angepassten Gradienten und Code-Farben',
  ]}, en: { title: 'Dark / Light Mode', items: [
    '<strong>Dark / Light Mode toggle</strong> (fixed button in the top-right corner)',
    '<strong>Auto mode</strong> follows <code>prefers-color-scheme</code> and reacts to live system changes; displays <code>auto</code> badge',
    'Manual preference saved in <code>localStorage</code> and restored on next visit',
    'Flash-free load via inline script in <code>&lt;head&gt;</code>',
    'Full Light Mode colour palette with adjusted gradients and code colours',
  ]}},
  { v: 'v1.0', de: { title: 'Initial Release', items: [
    'Blowfish ECB Verschlüsselung des <code>Data</code>-Parameters',
    'HMAC-SHA256 MAC-Berechnung',
    '<strong>Verschlüsselte Credential-Speicherung</strong> (AES-GCM) in <code>localStorage</code> mit PBKDF2-Schlüsselableitung',
    '<strong>Request-Log</strong> in <code>localStorage</code> (letzte 50 Einträge, aufklappbar, kopierbar)',
    '<strong>Neuer-Tab-Redirect</strong> — Die Paygate HPP öffnet in einem neuen Tab',
    'Parameter-Vorschau mit farbcodierter Klartext-Anzeige',
  ]}, en: { title: 'Initial Release', items: [
    'Blowfish ECB encryption of the <code>Data</code> parameter',
    'HMAC-SHA256 MAC calculation',
    '<strong>Encrypted credential storage</strong> (AES-GCM) in <code>localStorage</code> with PBKDF2 key derivation',
    '<strong>Request log</strong> in <code>localStorage</code> (last 50 entries, expandable, copyable)',
    '<strong>New tab redirect</strong> — Paygate HPP opens in a new tab',
    'Parameter preview with color-coded plain-text display',
  ]}},
];
