'use strict';

// Trusted, static help content rendered by index.html. Kept separate for readability.
const HELP_CONTENT = {
  de: `
    <nav class="help-jump" aria-label="Themen auf dieser Hilfeseite">
      <a href="#help-integration">Integration wählen</a>
      <a href="#help-usage">App verwenden</a>
      <a href="#help-docs">Dokumentation</a>
      <a href="#help-mobile-sdks">Mobile SDKs</a>
      <a class="nexi-plugin-jump" href="#help-plugins">Plugins</a>
      <a href="#help-testing">Test & Fehler</a>
      <a href="#help-privacy">Datenschutz</a>
    </nav>

    <section class="help-section help-priority" id="help-integration">
      <div class="help-section-heading">
        <span class="help-kicker">Startpunkt</span>
        <h2>Welche Integration passt?</h2>
        <p>Die Wahl betrifft nicht nur das Datenformat, sondern auch Architektur, Credential-Schutz und den späteren Betrieb.</p>
      </div>
      <div class="help-comparison">
        <article class="help-option">
          <div class="help-option-title"><span class="help-type-badge classic">Classic</span><h3>Classic Paygate</h3></div>
          <p>Der Shop erzeugt einen verschlüsselten <code>Data</code>-String mit <code>Len</code> und <code>MAC</code> und leitet den Browser an eine Paygate-Seite weiter.</p>
          <h4>Geeignet für</h4>
          <ul><li>Bestehende oder kompatible Classic-Anbindungen</li><li>Schnelle browserbasierte Weiterleitung zu Hosted Payment Page, Kreditkartenformular oder Pay By Link</li><li>Teams, die die etablierte Data/Len/MAC-Schnittstelle betreiben</li></ul>
          <h4>Vorteile</h4>
          <ul><li>Direkt aus diesem Tester start- und nachvollziehbar</li><li>Gehostete Zahlungsformulare reduzieren den Umgang mit Kartendaten</li><li>Reife, breit dokumentierte Schnittstelle</li></ul>
          <h4>Nachteile</h4>
          <ul><li>Proprietäre Blowfish-/MAC-Aufbereitung</li><li>Callbacks und Redirects müssen sauber verarbeitet werden</li><li>Weniger nah an üblichen JSON-/REST-Toolchains</li></ul>
        </article>
        <article class="help-option recommended">
          <div class="help-option-title"><span class="help-type-badge rest">REST</span><h3>REST API</h3></div>
          <p>Das Integrationssystem sendet strukturierte JSON-Requests über HTTPS. Dieser Tester baut die Requests nur zusammen; die Ausführung erfolgt serverseitig oder mit einem externen Tool.</p>
          <h4>Geeignet für</h4>
          <ul><li>Neue Backend- und API-zentrierte Integrationen</li><li>Teams mit cURL, PowerShell, Postman oder REST-Clients</li><li>Systeme, die standardisierte HTTP- und JSON-Verarbeitung bevorzugen</li></ul>
          <h4>Vorteile</h4>
          <ul><li>Standardisierte JSON-/HTTP-Workflows</li><li>Basic Auth oder OAuth2 Client Credentials</li><li>Klare Trennung zwischen Browser-UI und sicherem Backend</li></ul>
          <h4>Nachteile</h4>
          <ul><li>Keine direkte Ausführung aus dieser Browser-App</li><li>Für die sichere Ausführung ist ein Backend oder kontrolliertes externes Tool erforderlich</li><li>V1 und V2 besitzen unterschiedliche Endpunkte und Schemas</li></ul>
        </article>
      </div>
      <div class="help-callout"><strong>Faustregel:</strong> Bestehende Classic-Strecken bleiben häufig bei Data/Len/MAC. Für neue API-Projekte ist REST meist die natürlichere Architektur. Vertrag, freigeschaltete Funktionen und die projektspezifische Vorgabe bleiben jedoch maßgeblich.</div>
      <div class="help-version-grid">
        <article><span>REST V1</span><p>Ein gemeinsamer Payments-Endpunkt und das im Builder abgebildete V1-Schema. Die offizielle Dokumentation weist V1 primär bestehenden Händlern zu; in abgestimmten Projekten kann V1 weiterhin ausdrücklich vorgegeben sein.</p></article>
        <article><span>REST V2</span><p>Neuere, stärker nach Anwendungsfall getrennte Endpunkte für Checkout Sessions, Hosted Card Payments und Payment Links. Schema und Aktivierung vor der produktiven Integration prüfen.</p></article>
      </div>
    </section>

    <section class="help-section" id="help-usage">
      <div class="help-section-heading"><span class="help-kicker">Anleitung</span><h2>So verwendest du die App</h2></div>
      <ol class="help-steps">
        <li><strong>Credentials nur bei Bedarf eintragen</strong><span>Für Classic-Zahlungen sind Merchant ID, Blowfish- und HMAC-Passwort erforderlich; Classic-Statusabfragen benötigen nur Merchant ID und Blowfish-Passwort. REST-Requests lassen sich ohne Zugangsdaten mit sicheren Platzhaltern erstellen.</span></li>
        <li><strong>Schnittstelle und Use Case wählen</strong><span>In Schritt 2 zwischen Classic Paygate und REST API sowie zwischen Zahlungserstellung und Statusabfrage wechseln. MIT/CIT ist im UI bereits als späterer Use Case vorbereitet, aber noch nicht implementiert.</span></li>
        <li><strong>Request konfigurieren</strong><span>Für Zahlungen werden Zahlungsart, URLs, Betrag und weitere Parameter gepflegt. Statusabfragen verwenden je nach Schnittstelle PayID beziehungsweise Payment ID und/oder Transaction ID.</span></li>
        <li><strong>Vorschau erzeugen</strong><span>Classic zeigt Klartextparameter, verschlüsselte Daten, Länge und GET-URL. REST zeigt für Zahlungen JSON und für Statusabfragen einen body-losen GET-Request im gewählten Ausgabeformat.</span></li>
        <li><strong>Ausführung bewusst wählen</strong><span>Classic-Zahlungsseiten und Classic-Statusabfragen können in einem neuen Tab geöffnet werden. REST wird nicht vom Browser gesendet: Ausgabe kopieren und im Backend oder externen Tool ausführen.</span></li>
        <li><strong>Ergebnis prüfen</strong><span>Classic Requests, entschlüsselte Callbacks, REST-Redirects und manuell analysierte REST-JSON-Antworten können in den lokalen Logs nachvollzogen werden.</span></li>
      </ol>
    </section>

    <section class="help-section" id="help-docs">
      <div class="help-section-heading"><span class="help-kicker">Offizielle Quellen</span><h2>Dokumentation</h2><p>Die verlinkten Paygate-Seiten sind für die technische Umsetzung maßgeblich.</p></div>
      <div class="help-resource-grid">
        <a class="help-resource" href="https://developer.computop.com/pages/viewpage.action?pageId=25296736" target="_blank" rel="noopener"><span class="help-type-badge classic">Classic</span><strong>Einführung & Schnittstellen</strong><small>Überblick über Hosted Payment Page, paySSL und Server-to-Server-Anbindungen</small></a>
        <a class="help-resource" href="https://developer.computop.com/display/EN/Card+processing+-+common+form" target="_blank" rel="noopener"><span class="help-type-badge classic">Classic</span><strong>Kreditkartenformular</strong><small>Details zur gehosteten Kartenverarbeitung</small></a>
        <a class="help-resource" href="https://developer.computop.com/pages/viewpage.action?pageId=170952795" target="_blank" rel="noopener"><span class="help-type-badge rest">REST V1</span><strong>REST API V1</strong><small>Einführung, Sicherheit und Authentifizierung</small></a>
        <a class="help-resource" href="https://app.swaggerhub.com/apis-docs/Computop/Paygate_REST_API/1#/Payments" target="_blank" rel="noopener"><span class="help-type-badge rest">Swagger</span><strong>REST V1 OpenAPI</strong><small>Request-Schemas und Payments-Endpunkte</small></a>
        <a class="help-resource" href="https://developer.computop.com/display/EN/Status+inquiries" target="_blank" rel="noopener"><span class="help-type-badge classic">Classic</span><strong>Statusabfragen</strong><small>inquire.aspx über PayID und inquire24.aspx über Transaction ID</small></a>
        <a class="help-resource" href="https://developer.computop.com/pages/viewpage.action?pageId=179963381" target="_blank" rel="noopener"><span class="help-type-badge rest">REST V2</span><strong>REST API V2</strong><small>Übersicht und Integrationsansätze der aktuellen API</small></a>
        <div class="help-resource placeholder"><span class="help-type-badge pending">Offen</span><strong>REST V2 OpenAPI</strong><small>Direkter, final bestätigter Swagger-/OpenAPI-Link wird nachgereicht.</small></div>
      </div>
    </section>

    <section class="help-section mobile-sdk-section" id="help-mobile-sdks">
      <div class="help-section-heading"><span class="help-kicker">Native Apps</span><h2>Mobile SDKs für Android & iOS</h2><p>Die Nexi Paygate Mobile SDKs integrieren Karten- und Wallet-Zahlungen als nativen Checkout in mobile Apps. Sie stellen Eingabekomponenten, Validierung, EMV 3-D Secure, Ergebnisbehandlung und anpassbare Oberflächen bereit.</p></div>
      <div class="help-callout"><strong>Gemeinsamer Ablauf:</strong> Das Händler-Backend authentifiziert sich bei Paygate, erstellt einen Payment Intent und gibt ausschließlich <code>payment_intent_id</code> und ein kurzlebiges Access Token an die App. Das SDK sammelt die zahlungsartspezifischen Daten und bestätigt die Zahlung. Die App verarbeitet anschließend Erfolg, Abbruch oder Fehler. <strong>Client Secret und langlebige Händler-Credentials bleiben immer im Backend.</strong></div>
      <div class="plugin-resource-grid">
        <article class="plugin-card mobile-sdk-card">
          <div class="plugin-card-head"><div><h3>Android SDK</h3><p>Native Kotlin-/Jetpack-Compose-Integration für Kartenzahlungen und Google Pay.</p></div><span class="help-type-badge rest">Android</span></div>
          <ul class="mobile-sdk-details"><li>Android 5.0 / API 21 oder neuer</li><li>Kartenformular mit Validierung und nativem EMV 3-D Secure</li><li>Google Pay, Tokenisierung und wiederkehrende Zahlungen abhängig von der Händlerkonfiguration</li><li>Installation über Maven Central und anpassbares Material-3-UI</li></ul>
          <div class="plugin-actions">
            <a class="plugin-action" href="https://netsconnect.github.io/NexiPaygate-Android/" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4h8l4 4v12H7z"/><path d="M15 4v5h5M10 13h6M10 17h4"/></svg>API-Referenz</a>
            <a class="plugin-action download" href="https://github.com/netsconnect/NexiPaygate-Android" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 19c-4 1.5-4-2-6-2m12 4v-3.5c0-1 .1-1.4-.5-2 2.8-.3 5.5-1.4 5.5-6A4.6 4.6 0 0 0 19 6c.1-.3.5-1.5-.1-3 0 0-1.1-.3-3.7 1.3a13 13 0 0 0-6.7 0C5.9 2.7 4.8 3 4.8 3c-.6 1.5-.2 2.7-.1 3A4.6 4.6 0 0 0 3.5 9.5c0 4.6 2.8 5.7 5.5 6-.4.4-.6.8-.6 1.6V21"/></svg>GitHub</a>
          </div>
        </article>
        <article class="plugin-card mobile-sdk-card">
          <div class="plugin-card-head"><div><h3>iOS SDK</h3><p>Native Swift-/SwiftUI-Integration für Kartenzahlungen und Apple Pay.</p></div><span class="help-type-badge rest">iOS</span></div>
          <ul class="mobile-sdk-details"><li>iOS 15 oder neuer, Xcode 14+ und Swift 5.7+</li><li>Kartenformular mit Validierung und nativem EMV 3-D Secure</li><li>Apple Pay, Tokenisierung und wiederkehrende Zahlungen abhängig von der Händlerkonfiguration</li><li>Installation über Swift Package Manager, CocoaPods oder manuell</li></ul>
          <div class="plugin-actions">
            <a class="plugin-action" href="https://netsconnect.github.io/NexiPaygate-iOS/" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4h8l4 4v12H7z"/><path d="M15 4v5h5M10 13h6M10 17h4"/></svg>API-Referenz</a>
            <a class="plugin-action download" href="https://github.com/netsconnect/NexiPaygate-iOS" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 19c-4 1.5-4-2-6-2m12 4v-3.5c0-1 .1-1.4-.5-2 2.8-.3 5.5-1.4 5.5-6A4.6 4.6 0 0 0 19 6c.1-.3.5-1.5-.1-3 0 0-1.1-.3-3.7 1.3a13 13 0 0 0-6.7 0C5.9 2.7 4.8 3 4.8 3c-.6 1.5-.2 2.7-.1 3A4.6 4.6 0 0 0 3.5 9.5c0 4.6 2.8 5.7 5.5 6-.4.4-.6.8-.6 1.6V21"/></svg>GitHub</a>
          </div>
        </article>
      </div>
      <div class="help-warning"><strong>Wichtig:</strong> Ein Mobile SDK ersetzt kein Händler-Backend. Zahlungsstatus und Ergebnis sollten serverseitig verifiziert werden; Zugangsdaten und Token-Erzeugung gehören nicht in den ausgelieferten App-Code. Vor der produktiven Integration immer die aktuellen README-, API- und Release-Hinweise der Repositories prüfen.</div>
    </section>

    <section class="help-section nexi-plugin-section" id="help-plugins">
      <div class="help-section-heading"><span class="help-kicker">Nexi Paygate</span><h2>Shop-Plugins</h2><p>Offizielle Plugin-Übersicht aus der Nexi Paygate Dokumentation. Die Links öffnen Dokumentation oder Download beim jeweiligen Anbieter.</p></div>
      <div class="plugin-resource-grid">
        <article class="plugin-card">
          <div class="plugin-card-head"><div><h3>Magento</h3><p>Plugin-Paket mit Anbieter-Dokumentation und GitHub-Releases.</p></div><span class="help-type-badge rest">Plugin</span></div>
          <div class="plugin-actions">
            <a class="plugin-action" href="https://wiki.fatchip.de/public/magento2-fatchipnexipayment" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4h8l4 4v12H7z"/><path d="M15 4v5h5M10 13h6M10 17h4"/></svg>Dokumentation</a>
            <a class="plugin-action download" href="https://github.com/FATCHIP-GmbH/plugin-magento2-computop/releases" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/></svg>Download</a>
          </div>
        </article>
        <article class="plugin-card">
          <div class="plugin-card-head"><div><h3>Shopware 6</h3><p>Dokumentation als PDF und zentraler Download-Bereich.</p></div><span class="help-type-badge rest">Plugin</span></div>
          <div class="plugin-actions">
            <a class="plugin-action" href="https://computop.ideal-shops.de/download/computop-paygate-dokumentation-shopware6.pdf" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4h8l4 4v12H7z"/><path d="M15 4v5h5M10 13h6M10 17h4"/></svg>Dokumentation</a>
            <a class="plugin-action download" href="https://computop.ideal-shops.de/nexi/Downloads/" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/></svg>Download</a>
          </div>
        </article>
        <article class="plugin-card">
          <div class="plugin-card-head"><div><h3>Oxid 6</h3><p>Fatchip-Dokumentation und Plugin-Download für OXID eShop 6.</p></div><span class="help-type-badge rest">Plugin</span></div>
          <div class="plugin-actions">
            <a class="plugin-action" href="https://wiki.fatchip.de/public/oxid6-fatchipctpayment" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4h8l4 4v12H7z"/><path d="M15 4v5h5M10 13h6M10 17h4"/></svg>Dokumentation</a>
            <a class="plugin-action download" href="https://www.fatchip.de/Plugins/OXID-eShop/OXID-6-Nexi-Paygate.html" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/></svg>Download</a>
          </div>
        </article>
        <article class="plugin-card">
          <div class="plugin-card-head"><div><h3>WooCommerce</h3><p>Dokumentations-PDF und direkter ZIP-Download für WordPress/WooCommerce.</p></div><span class="help-type-badge rest">Plugin</span></div>
          <div class="plugin-actions">
            <a class="plugin-action" href="https://www.patworx.de/computop/files/DokuWooCommerce.pdf" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4h8l4 4v12H7z"/><path d="M15 4v5h5M10 13h6M10 17h4"/></svg>Dokumentation</a>
            <a class="plugin-action download" href="https://www.patworx.de/nexi-paygate/nexi-paygate.zip" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/></svg>Download</a>
          </div>
        </article>
      </div>
      <div class="help-callout"><strong>Quelle:</strong> <a href="https://docs.paygate.nexigroup.com/nexi-developer/plugins" target="_blank" rel="noopener">Nexi Paygate Plugin-Dokumentation</a>. Vor einer produktiven Installation immer Version, Kompatibilität und Anbieterhinweise prüfen.</div>
    </section>

    <section class="help-section" id="help-testing">
      <div class="help-section-heading"><span class="help-kicker">Validierung</span><h2>Testdaten & Fehlersuche</h2></div>
      <div class="help-resource-grid compact">
        <a class="help-resource" href="https://developer.computop.com/display/EN/Test+Guide" target="_blank" rel="noopener"><span class="help-resource-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M6 3h12a2 2 0 0 1 2 2v16H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z"/><path d="M8 3v18M8 7h8"/></svg></span><strong>Test Guide</strong><small>Allgemeiner Einstieg in Test- und Simulationsmöglichkeiten</small></a>
        <a class="help-resource" href="https://developer.computop.com/display/EN/Test+credit+card" target="_blank" rel="noopener"><span class="help-resource-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2.5"/><path d="M3 9h18M7 15h3"/></svg></span><strong>Test-Kreditkarten</strong><small>Offizielle Karten, 3-D-Secure-Szenarien und Testhinweise</small></a>
        <a class="help-resource" href="https://developer.computop.com/display/EN/A4+Error+codes" target="_blank" rel="noopener"><span class="help-resource-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 3 2.8 19a1.4 1.4 0 0 0 1.2 2h16a1.4 1.4 0 0 0 1.2-2z"/><path d="M12 9v5M12 17.5v.01"/></svg></span><strong>Fehler- und Response-Codes</strong><small>Aufbau der Codes, betroffene Module und Parameterfehler</small></a>
        <a class="help-resource" href="https://computop.statuspage.io/" target="_blank" rel="noopener"><span class="help-resource-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M3 12h4l2.2-5 4.1 10 2.2-5H21"/><circle cx="12" cy="12" r="9"/></svg></span><strong>Paygate Status</strong><small>Aktuelle Betriebs- und Störungsinformationen</small></a>
      </div>
      <div class="help-callout"><strong>Bei Fehlern zuerst prüfen:</strong> Merchant ID und zugehörige Schlüssel, Test-/Produktivsystem, Betrag in kleinster Währungseinheit, Pflichtfelder, eindeutige Transaktions-ID sowie bei Classic die MAC-Reihenfolge und <code>Len</code>.</div>
    </section>

    <section class="help-section" id="help-privacy">
      <div class="help-section-heading"><span class="help-kicker">Sicherheit</span><h2>Datenschutz & Credentials</h2></div>
      <div class="help-privacy-grid">
        <article><h3>Was lokal bleibt</h3><p>Request-Aufbereitung, Verschlüsselung und REST-Codegenerierung erfolgen im Browser. Classic- und Response-Logs liegen lokal in IndexedDB, mit LocalStorage-Fallback.</p></article>
        <article><h3>Wann Daten das Gerät verlassen</h3><p>Bei Classic erst beim bewussten Öffnen der Paygate-URL. REST sendet diese App grundsätzlich nicht. Externe Dokumentationslinks verlassen beim Öffnen die App.</p></article>
        <article><h3>Gespeicherte Credentials</h3><p>Profile werden AES-GCM-verschlüsselt gespeichert. Standardmäßig basiert der Schlüssel auf einer app-eigenen statischen Passphrase; mit einem optionalen Master-Passwort (Schritt 1 → Profile) wird der Schlüssel aus deinem Passwort abgeleitet und ist nicht mehr aus dem Quellcode rekonstruierbar. Ein Passwortmanager oder Backend-Secret-Store wird dadurch trotzdem nicht ersetzt.</p></article>
        <article><h3>Empfehlung</h3><p>Test-Credentials bevorzugen, produktive Secrets nur lokal und kurzzeitig verwenden, REST-Ausgaben standardmäßig mit Platzhaltern erzeugen und Browser-/Shell-History beachten.</p></article>
        <article><h3>Callback-Empfänger</h3><p>Ist der Callback-Empfänger aktiviert, leitet das Paygate Antwort-Parameter per URL auf diese Seite zurück; sie passieren dabei die Server-Logs des Hostings (GitHub Pages/CDN). Classic-Antworten sind dabei Blowfish-verschlüsselt und werden ausschließlich lokal im Browser entschlüsselt. Für echte Transaktionen empfiehlt sich der Simulationsmodus.</p></article>
      </div>
      <div class="help-warning"><strong>Wichtig:</strong> REST API-Key oder OAuth Client Secret gehören im Produktivbetrieb in ein Backend oder Secret-Management-System. Sie sollten nicht aus öffentlich ausgeliefertem Browser-Code an die API gesendet werden.</div>
    </section>
  `,
  en: `
    <nav class="help-jump" aria-label="Topics on this help page">
      <a href="#help-integration">Choose integration</a><a href="#help-usage">Use the app</a><a href="#help-docs">Documentation</a><a href="#help-mobile-sdks">Mobile SDKs</a><a class="nexi-plugin-jump" href="#help-plugins">Plugins</a><a href="#help-testing">Testing & errors</a><a href="#help-privacy">Privacy</a>
    </nav>
    <section class="help-section help-priority" id="help-integration">
      <div class="help-section-heading"><span class="help-kicker">Starting point</span><h2>Which integration fits?</h2><p>The choice affects data format, architecture, credential protection and ongoing operations.</p></div>
      <div class="help-comparison">
        <article class="help-option"><div class="help-option-title"><span class="help-type-badge classic">Classic</span><h3>Classic Paygate</h3></div><p>The shop creates an encrypted <code>Data</code> string with <code>Len</code> and <code>MAC</code>, then redirects the browser to a Paygate page.</p><h4>Suitable for</h4><ul><li>Existing or compatible Classic integrations</li><li>Browser redirects to Hosted Payment Page, credit card form or Pay By Link</li><li>Teams operating the established Data/Len/MAC interface</li></ul><h4>Advantages</h4><ul><li>Can be launched and inspected directly from this tester</li><li>Hosted forms reduce direct handling of card data</li><li>Mature and broadly documented interface</li></ul><h4>Disadvantages</h4><ul><li>Proprietary Blowfish and MAC preparation</li><li>Callbacks and redirects require careful handling</li><li>Less aligned with standard JSON/REST tooling</li></ul></article>
        <article class="help-option recommended"><div class="help-option-title"><span class="help-type-badge rest">REST</span><h3>REST API</h3></div><p>The integration system sends structured JSON over HTTPS. This tester only assembles requests; execution takes place server-side or in an external tool.</p><h4>Suitable for</h4><ul><li>New backend and API-centred integrations</li><li>Teams using cURL, PowerShell, Postman or REST clients</li><li>Systems preferring standard HTTP and JSON processing</li></ul><h4>Advantages</h4><ul><li>Standard JSON/HTTP workflows</li><li>Basic Auth or OAuth2 Client Credentials</li><li>Clear separation between browser UI and secure backend</li></ul><h4>Disadvantages</h4><ul><li>No direct execution from this browser app</li><li>Secure execution requires a backend or controlled external tool</li><li>V1 and V2 use different endpoints and schemas</li></ul></article>
      </div>
      <div class="help-callout"><strong>Rule of thumb:</strong> Existing Classic flows often remain on Data/Len/MAC. REST is usually the more natural architecture for new API projects. Contract, enabled features and project requirements remain decisive.</div>
      <div class="help-version-grid"><article><span>REST V1</span><p>A shared payments endpoint and the V1 schema represented by the builder. Official documentation primarily assigns V1 to existing merchants, though agreed projects may still explicitly require it.</p></article><article><span>REST V2</span><p>Newer, use-case-specific endpoints for checkout sessions, hosted card payments and payment links. Verify schema and account activation before production integration.</p></article></div>
    </section>
    <section class="help-section" id="help-usage"><div class="help-section-heading"><span class="help-kicker">Guide</span><h2>How to use the app</h2></div><ol class="help-steps"><li><strong>Enter credentials only when needed</strong><span>Classic requires Merchant ID plus Blowfish and HMAC passwords for payment creation; Classic status inquiries only require Merchant ID and Blowfish password. REST requests can be built without credentials using secure placeholders.</span></li><li><strong>Choose interface and use case</strong><span>In Step 2 select Classic Paygate or REST API and choose payment creation or status inquiry. MIT/CIT is visible as a future placeholder but is not implemented yet.</span></li><li><strong>Configure the request</strong><span>Payments use payment type, URLs, amount and further parameters. Status inquiries use Payment ID/PayID and/or Transaction ID depending on the selected interface.</span></li><li><strong>Generate a preview</strong><span>Classic shows plain parameters, encrypted data, length and GET URL. REST shows JSON for payments and a body-less GET request for status inquiries in the selected output format.</span></li><li><strong>Choose execution deliberately</strong><span>Classic payment pages and Classic status inquiries can open in a new tab. REST requests are not sent by the browser: copy them to a backend or external tool.</span></li><li><strong>Review the result</strong><span>Classic requests, decrypted callbacks, REST redirects and manually analysed REST JSON responses are available in the local logs.</span></li></ol></section>
    <section class="help-section" id="help-docs"><div class="help-section-heading"><span class="help-kicker">Official sources</span><h2>Documentation</h2><p>The linked Paygate pages are authoritative for implementation.</p></div><div class="help-resource-grid">
      <a class="help-resource" href="https://developer.computop.com/pages/viewpage.action?pageId=25296736" target="_blank" rel="noopener"><span class="help-type-badge classic">Classic</span><strong>Introduction & interfaces</strong><small>Hosted Payment Page, paySSL and server-to-server overview</small></a><a class="help-resource" href="https://developer.computop.com/display/EN/Card+processing+-+common+form" target="_blank" rel="noopener"><span class="help-type-badge classic">Classic</span><strong>Credit card form</strong><small>Hosted card processing details</small></a><a class="help-resource" href="https://developer.computop.com/pages/viewpage.action?pageId=170952795" target="_blank" rel="noopener"><span class="help-type-badge rest">REST V1</span><strong>REST API V1</strong><small>Introduction, security and authentication</small></a><a class="help-resource" href="https://app.swaggerhub.com/apis-docs/Computop/Paygate_REST_API/1#/Payments" target="_blank" rel="noopener"><span class="help-type-badge rest">Swagger</span><strong>REST V1 OpenAPI</strong><small>Request schemas and payment endpoints</small></a><a class="help-resource" href="https://developer.computop.com/display/EN/Status+inquiries" target="_blank" rel="noopener"><span class="help-type-badge classic">Classic</span><strong>Status inquiries</strong><small>inquire.aspx by PayID and inquire24.aspx by Transaction ID</small></a><a class="help-resource" href="https://developer.computop.com/pages/viewpage.action?pageId=179963381" target="_blank" rel="noopener"><span class="help-type-badge rest">REST V2</span><strong>REST API V2</strong><small>Current API overview and integration approaches</small></a><div class="help-resource placeholder"><span class="help-type-badge pending">Pending</span><strong>REST V2 OpenAPI</strong><small>A final confirmed direct Swagger/OpenAPI link will be added.</small></div>
    </div></section>
    <section class="help-section mobile-sdk-section" id="help-mobile-sdks">
      <div class="help-section-heading"><span class="help-kicker">Native apps</span><h2>Mobile SDKs for Android & iOS</h2><p>The Nexi Paygate Mobile SDKs provide native card and wallet checkout components for mobile apps, including input validation, EMV 3-D Secure, result handling and customisable UI.</p></div>
      <div class="help-callout"><strong>Shared flow:</strong> The merchant backend authenticates with Paygate, creates a Payment Intent and returns only the <code>payment_intent_id</code> plus a short-lived access token to the app. The SDK collects payment-method data and confirms the payment. The app then handles success, cancellation or failure. <strong>Client secrets and long-lived merchant credentials always remain in the backend.</strong></div>
      <div class="plugin-resource-grid">
        <article class="plugin-card mobile-sdk-card"><div class="plugin-card-head"><div><h3>Android SDK</h3><p>Native Kotlin and Jetpack Compose integration for card payments and Google Pay.</p></div><span class="help-type-badge rest">Android</span></div><ul class="mobile-sdk-details"><li>Android 5.0 / API 21 or later</li><li>Validated card entry and native EMV 3-D Secure</li><li>Google Pay, tokenisation and recurring payments depending on merchant configuration</li><li>Maven Central distribution and customisable Material 3 UI</li></ul><div class="plugin-actions"><a class="plugin-action" href="https://netsconnect.github.io/NexiPaygate-Android/" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4h8l4 4v12H7z"/><path d="M15 4v5h5M10 13h6M10 17h4"/></svg>API reference</a><a class="plugin-action download" href="https://github.com/netsconnect/NexiPaygate-Android" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 19c-4 1.5-4-2-6-2m12 4v-3.5c0-1 .1-1.4-.5-2 2.8-.3 5.5-1.4 5.5-6A4.6 4.6 0 0 0 19 6c.1-.3.5-1.5-.1-3 0 0-1.1-.3-3.7 1.3a13 13 0 0 0-6.7 0C5.9 2.7 4.8 3 4.8 3c-.6 1.5-.2 2.7-.1 3A4.6 4.6 0 0 0 3.5 9.5c0 4.6 2.8 5.7 5.5 6-.4.4-.6.8-.6 1.6V21"/></svg>GitHub</a></div></article>
        <article class="plugin-card mobile-sdk-card"><div class="plugin-card-head"><div><h3>iOS SDK</h3><p>Native Swift and SwiftUI integration for card payments and Apple Pay.</p></div><span class="help-type-badge rest">iOS</span></div><ul class="mobile-sdk-details"><li>iOS 15 or later, Xcode 14+ and Swift 5.7+</li><li>Validated card entry and native EMV 3-D Secure</li><li>Apple Pay, tokenisation and recurring payments depending on merchant configuration</li><li>Swift Package Manager, CocoaPods or manual installation</li></ul><div class="plugin-actions"><a class="plugin-action" href="https://netsconnect.github.io/NexiPaygate-iOS/" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4h8l4 4v12H7z"/><path d="M15 4v5h5M10 13h6M10 17h4"/></svg>API reference</a><a class="plugin-action download" href="https://github.com/netsconnect/NexiPaygate-iOS" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 19c-4 1.5-4-2-6-2m12 4v-3.5c0-1 .1-1.4-.5-2 2.8-.3 5.5-1.4 5.5-6A4.6 4.6 0 0 0 19 6c.1-.3.5-1.5-.1-3 0 0-1.1-.3-3.7 1.3a13 13 0 0 0-6.7 0C5.9 2.7 4.8 3 4.8 3c-.6 1.5-.2 2.7-.1 3A4.6 4.6 0 0 0 3.5 9.5c0 4.6 2.8 5.7 5.5 6-.4.4-.6.8-.6 1.6V21"/></svg>GitHub</a></div></article>
      </div>
      <div class="help-warning"><strong>Important:</strong> A Mobile SDK does not replace the merchant backend. Verify payment status and results server-side; credentials and token creation do not belong in distributed app code. Always review the latest README, API and release notes before production integration.</div>
    </section>
    <section class="help-section nexi-plugin-section" id="help-plugins"><div class="help-section-heading"><span class="help-kicker">Nexi Paygate</span><h2>Shop plugins</h2><p>Official plugin overview from the Nexi Paygate documentation. Links open documentation or download pages at the relevant provider.</p></div><div class="plugin-resource-grid">
      <article class="plugin-card"><div class="plugin-card-head"><div><h3>Magento</h3><p>Plugin package with provider documentation and GitHub releases.</p></div><span class="help-type-badge rest">Plugin</span></div><div class="plugin-actions"><a class="plugin-action" href="https://wiki.fatchip.de/public/magento2-fatchipnexipayment" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4h8l4 4v12H7z"/><path d="M15 4v5h5M10 13h6M10 17h4"/></svg>Documentation</a><a class="plugin-action download" href="https://github.com/FATCHIP-GmbH/plugin-magento2-computop/releases" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/></svg>Download</a></div></article>
      <article class="plugin-card"><div class="plugin-card-head"><div><h3>Shopware 6</h3><p>Documentation PDF and central download area.</p></div><span class="help-type-badge rest">Plugin</span></div><div class="plugin-actions"><a class="plugin-action" href="https://computop.ideal-shops.de/download/computop-paygate-dokumentation-shopware6.pdf" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4h8l4 4v12H7z"/><path d="M15 4v5h5M10 13h6M10 17h4"/></svg>Documentation</a><a class="plugin-action download" href="https://computop.ideal-shops.de/nexi/Downloads/" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/></svg>Download</a></div></article>
      <article class="plugin-card"><div class="plugin-card-head"><div><h3>Oxid 6</h3><p>Fatchip documentation and plugin download for OXID eShop 6.</p></div><span class="help-type-badge rest">Plugin</span></div><div class="plugin-actions"><a class="plugin-action" href="https://wiki.fatchip.de/public/oxid6-fatchipctpayment" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4h8l4 4v12H7z"/><path d="M15 4v5h5M10 13h6M10 17h4"/></svg>Documentation</a><a class="plugin-action download" href="https://www.fatchip.de/Plugins/OXID-eShop/OXID-6-Nexi-Paygate.html" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/></svg>Download</a></div></article>
      <article class="plugin-card"><div class="plugin-card-head"><div><h3>WooCommerce</h3><p>Documentation PDF and direct ZIP download for WordPress/WooCommerce.</p></div><span class="help-type-badge rest">Plugin</span></div><div class="plugin-actions"><a class="plugin-action" href="https://www.patworx.de/computop/files/DokuWooCommerce.pdf" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4h8l4 4v12H7z"/><path d="M15 4v5h5M10 13h6M10 17h4"/></svg>Documentation</a><a class="plugin-action download" href="https://www.patworx.de/nexi-paygate/nexi-paygate.zip" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/></svg>Download</a></div></article>
    </div><div class="help-callout"><strong>Source:</strong> <a href="https://docs.paygate.nexigroup.com/nexi-developer/plugins" target="_blank" rel="noopener">Nexi Paygate plugin documentation</a>. Always verify version, compatibility and provider notes before production installation.</div></section>
    <section class="help-section" id="help-testing"><div class="help-section-heading"><span class="help-kicker">Validation</span><h2>Test data & troubleshooting</h2></div><div class="help-resource-grid compact"><a class="help-resource" href="https://developer.computop.com/display/EN/Test+Guide" target="_blank" rel="noopener"><span class="help-resource-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M6 3h12a2 2 0 0 1 2 2v16H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z"/><path d="M8 3v18M8 7h8"/></svg></span><strong>Test Guide</strong><small>General test and simulation guidance</small></a><a class="help-resource" href="https://developer.computop.com/display/EN/Test+credit+card" target="_blank" rel="noopener"><span class="help-resource-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2.5"/><path d="M3 9h18M7 15h3"/></svg></span><strong>Test credit cards</strong><small>Official cards, 3-D Secure scenarios and notes</small></a><a class="help-resource" href="https://developer.computop.com/display/EN/A4+Error+codes" target="_blank" rel="noopener"><span class="help-resource-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 3 2.8 19a1.4 1.4 0 0 0 1.2 2h16a1.4 1.4 0 0 0 1.2-2z"/><path d="M12 9v5M12 17.5v.01"/></svg></span><strong>Error and response codes</strong><small>Code structure, modules and parameter errors</small></a><a class="help-resource" href="https://computop.statuspage.io/" target="_blank" rel="noopener"><span class="help-resource-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M3 12h4l2.2-5 4.1 10 2.2-5H21"/><circle cx="12" cy="12" r="9"/></svg></span><strong>Paygate status</strong><small>Current service and incident information</small></a></div><div class="help-callout"><strong>Check first:</strong> Merchant ID and matching keys, test versus production environment, amount in minor units, required fields, unique transaction ID and, for Classic, MAC order and <code>Len</code>.</div></section>
    <section class="help-section" id="help-privacy"><div class="help-section-heading"><span class="help-kicker">Security</span><h2>Privacy & credentials</h2></div><div class="help-privacy-grid"><article><h3>What stays local</h3><p>Request preparation, encryption and REST code generation run in the browser. Classic and response logs are stored locally in IndexedDB with a LocalStorage fallback.</p></article><article><h3>When data leaves the device</h3><p>For Classic, only when the Paygate URL is deliberately opened. This app never sends REST requests. External documentation links leave the app when opened.</p></article><article><h3>Stored credentials</h3><p>Profiles use AES-GCM encryption. By default the key is based on an application-owned static passphrase; with an optional master password (step 1 → profiles) the key is derived from your password and can no longer be reconstructed from the source code. This still does not replace a password manager or protected backend secret store.</p></article><article><h3>Recommendation</h3><p>Prefer test credentials, use production secrets locally and briefly, keep REST placeholders enabled by default and consider browser and shell history.</p></article><article><h3>Callback receiver</h3><p>When the callback receiver is enabled, Paygate redirects response parameters back to this page via URL; they pass through the hosting provider's server logs (GitHub Pages/CDN). Classic responses remain Blowfish-encrypted and are decrypted exclusively in your browser. Prefer simulation mode for anything resembling real transactions.</p></article></div><div class="help-warning"><strong>Important:</strong> In production, REST API keys or OAuth client secrets belong in a backend or secret-management system, not in publicly delivered browser code.</div></section>
  `
};
